def test_quantile_nat(self):
    df = DataFrame({'a': [pd.NaT, pd.NaT, pd.NaT]})
    res = df.quantile(0.5, numeric_only=False)
    exp = Series([pd.NaT], index=['a'], name=0.5)
    tm.assert_series_equal(res, exp)
    res = df.quantile([0.5], numeric_only=False)
    exp = DataFrame({'a': [pd.NaT]}, index=[0.5])
    tm.assert_frame_equal(res, exp)
    df = DataFrame({'a': [pd.Timestamp('2012-01-01'), pd.Timestamp('2012-01-02'), pd.Timestamp('2012-01-03')], 'b': [pd.NaT, pd.NaT, pd.NaT]})
    res = df.quantile(0.5, numeric_only=False)
    exp = Series([pd.Timestamp('2012-01-02'), pd.NaT], index=['a', 'b'], name=0.5)
    tm.assert_series_equal(res, exp)
    res = df.quantile([0.5], numeric_only=False)
    exp = DataFrame([[pd.Timestamp('2012-01-02'), pd.NaT]], index=[0.5], columns=['a', 'b'])
    tm.assert_frame_equal(res, exp)