@pytest.mark.parametrize('tz', timezones)
@pytest.mark.parametrize('freq', ['D', 'M', 'S', 'N'])
@pytest.mark.parametrize('date', ['2014-03-07', '2014-01-01 09:00', '2014-01-01 00:00:00.000000001'])
def test_repr(self, date, freq, tz):
    freq_repr = "'{0}'".format(freq)
    if tz.startswith('dateutil'):
        tz_repr = tz.replace('dateutil', '')
    else:
        tz_repr = tz
    date_only = Timestamp(date)
    assert date in repr(date_only)
    assert tz_repr not in repr(date_only)
    assert freq_repr not in repr(date_only)
    assert date_only == eval(repr(date_only))
    date_tz = Timestamp(date, tz=tz)
    assert date in repr(date_tz)
    assert tz_repr in repr(date_tz)
    assert freq_repr not in repr(date_tz)
    assert date_tz == eval(repr(date_tz))
    date_freq = Timestamp(date, freq=freq)
    assert date in repr(date_freq)
    assert tz_repr not in repr(date_freq)
    assert freq_repr in repr(date_freq)
    assert date_freq == eval(repr(date_freq))
    date_tz_freq = Timestamp(date, tz=tz, freq=freq)
    assert date in repr(date_tz_freq)
    assert tz_repr in repr(date_tz_freq)
    assert freq_repr in repr(date_tz_freq)
    assert date_tz_freq == eval(repr(date_tz_freq))