def test_startswith(self):
    values = Series(['om', np.nan, 'foo_nom', 'nom', 'bar_foo', np.nan, 'foo'])
    result = values.str.startswith('foo')
    exp = Series([False, np.nan, True, False, False, np.nan, True])
    tm.assert_series_equal(result, exp)
    result = values.str.startswith('foo', na=True)
    tm.assert_series_equal(result, exp.fillna(True).astype(bool))
    mixed = np.array(['a', np.nan, 'b', True, datetime.today(), 'foo', None, 1, 2.0], dtype=np.object_)
    rs = strings.str_startswith(mixed, 'f')
    xp = np.array([False, np.nan, False, np.nan, np.nan, True, np.nan, np.nan, np.nan], dtype=np.object_)
    tm.assert_numpy_array_equal(rs, xp)
    rs = Series(mixed).str.startswith('f')
    assert isinstance(rs, Series)
    xp = Series([False, np.nan, False, np.nan, np.nan, True, np.nan, np.nan, np.nan])
    tm.assert_series_equal(rs, xp)