def test_match(self):
    values = Series(['fooBAD__barBAD', np.nan, 'foo'])
    result = values.str.match('.*(BAD[_]+).*(BAD)')
    exp = Series([True, np.nan, False])
    tm.assert_series_equal(result, exp)
    values = Series(['fooBAD__barBAD', np.nan, 'foo'])
    result = values.str.match('.*BAD[_]+.*BAD')
    exp = Series([True, np.nan, False])
    tm.assert_series_equal(result, exp)
    mixed = Series(['aBAD_BAD', np.nan, 'BAD_b_BAD', True, datetime.today(), 'foo', None, 1, 2.0])
    rs = Series(mixed).str.match('.*(BAD[_]+).*(BAD)')
    xp = Series([True, np.nan, True, np.nan, np.nan, False, np.nan, np.nan, np.nan])
    assert isinstance(rs, Series)
    tm.assert_series_equal(rs, xp)
    res = Series(['a', 0, np.nan]).str.match('a', na=False)
    exp = Series([True, False, False])
    tm.assert_series_equal(exp, res)
    res = Series(['a', 0, np.nan]).str.match('a')
    exp = Series([True, np.nan, np.nan])
    tm.assert_series_equal(exp, res)