@pytest.mark.parametrize('op', [operator.add, operator.sub, operator.mul, operator.floordiv, operator.truediv, operator.pow])
def test_arithmetic_with_frame_or_series(self, op):
    index = pd.RangeIndex(5)
    other = pd.Series(np.random.randn(5))
    expected = op(pd.Series(index), other)
    result = op(index, other)
    tm.assert_series_equal(result, expected)
    other = pd.DataFrame(np.random.randn(2, 5))
    expected = op(pd.DataFrame([index, index]), other)
    result = op(index, other)
    tm.assert_frame_equal(result, expected)