def test_datelike(self):
    v1 = Timestamp('20130101 09:00:00.00004')
    v2 = Timestamp('20130101')
    x = Series([v1, v1, v1, v2, v2, v1])
    codes, uniques = algos.factorize(x)
    exp = np.array([0, 0, 0, 1, 1, 0], dtype=np.intp)
    tm.assert_numpy_array_equal(codes, exp)
    exp = DatetimeIndex([v1, v2])
    tm.assert_index_equal(uniques, exp)
    codes, uniques = algos.factorize(x, sort=True)
    exp = np.array([1, 1, 1, 0, 0, 1], dtype=np.intp)
    tm.assert_numpy_array_equal(codes, exp)
    exp = DatetimeIndex([v2, v1])
    tm.assert_index_equal(uniques, exp)
    v1 = pd.Period('201302', freq='M')
    v2 = pd.Period('201303', freq='M')
    x = Series([v1, v1, v1, v2, v2, v1])
    codes, uniques = algos.factorize(x)
    exp = np.array([0, 0, 0, 1, 1, 0], dtype=np.intp)
    tm.assert_numpy_array_equal(codes, exp)
    tm.assert_index_equal(uniques, pd.PeriodIndex([v1, v2]))
    codes, uniques = algos.factorize(x, sort=True)
    exp = np.array([0, 0, 0, 1, 1, 0], dtype=np.intp)
    tm.assert_numpy_array_equal(codes, exp)
    tm.assert_index_equal(uniques, pd.PeriodIndex([v1, v2]))
    v1 = pd.to_timedelta('1 day 1 min')
    v2 = pd.to_timedelta('1 day')
    x = Series([v1, v2, v1, v1, v2, v2, v1])
    codes, uniques = algos.factorize(x)
    exp = np.array([0, 1, 0, 0, 1, 1, 0], dtype=np.intp)
    tm.assert_numpy_array_equal(codes, exp)
    tm.assert_index_equal(uniques, pd.to_timedelta([v1, v2]))
    codes, uniques = algos.factorize(x, sort=True)
    exp = np.array([1, 0, 1, 1, 0, 0, 1], dtype=np.intp)
    tm.assert_numpy_array_equal(codes, exp)
    tm.assert_index_equal(uniques, pd.to_timedelta([v2, v1]))