def test_contains(self):
    values = np.array(['foo', np.nan, 'fooommm__foo', 'mmm_', 'foommm[_]+bar'], dtype=np.object_)
    pat = 'mmm[_]+'
    result = strings.str_contains(values, pat)
    expected = np.array([False, np.nan, True, True, False], dtype=np.object_)
    tm.assert_numpy_array_equal(result, expected)
    result = strings.str_contains(values, pat, regex=False)
    expected = np.array([False, np.nan, False, False, True], dtype=np.object_)
    tm.assert_numpy_array_equal(result, expected)
    values = np.array(['foo', 'xyz', 'fooommm__foo', 'mmm_'], dtype=object)
    result = strings.str_contains(values, pat)
    expected = np.array([False, False, True, True])
    assert result.dtype == np.bool_
    tm.assert_numpy_array_equal(result, expected)
    values = np.array(['Foo', 'xYz', 'fOOomMm__fOo', 'MMM_'], dtype=object)
    result = strings.str_contains(values, 'FOO|mmm', case=False)
    expected = np.array([True, False, True, True])
    tm.assert_numpy_array_equal(result, expected)
    result = strings.str_contains(values, 'foo', regex=False, case=False)
    expected = np.array([True, False, True, False])
    tm.assert_numpy_array_equal(result, expected)
    mixed = np.array(['a', np.nan, 'b', True, datetime.today(), 'foo', None, 1, 2.0], dtype=object)
    rs = strings.str_contains(mixed, 'o')
    xp = np.array([False, np.nan, False, np.nan, np.nan, True, np.nan, np.nan, np.nan], dtype=np.object_)
    tm.assert_numpy_array_equal(rs, xp)
    rs = Series(mixed).str.contains('o')
    xp = Series([False, np.nan, False, np.nan, np.nan, True, np.nan, np.nan, np.nan])
    assert isinstance(rs, Series)
    tm.assert_series_equal(rs, xp)
    values = np.array(['foo', np.nan, 'fooommm__foo', 'mmm_'], dtype=np.object_)
    pat = 'mmm[_]+'
    result = strings.str_contains(values, pat)
    expected = np.array([False, np.nan, True, True], dtype=np.object_)
    tm.assert_numpy_array_equal(result, expected)
    result = strings.str_contains(values, pat, na=False)
    expected = np.array([False, False, True, True])
    tm.assert_numpy_array_equal(result, expected)
    values = np.array(['foo', 'xyz', 'fooommm__foo', 'mmm_'], dtype=np.object_)
    result = strings.str_contains(values, pat)
    expected = np.array([False, False, True, True])
    assert result.dtype == np.bool_
    tm.assert_numpy_array_equal(result, expected)