def test_contains_nan(self):
    s = Series([np.nan, np.nan, np.nan], dtype=np.object_)
    result = s.str.contains('foo', na=False)
    expected = Series([False, False, False], dtype=np.bool_)
    tm.assert_series_equal(result, expected)
    result = s.str.contains('foo', na=True)
    expected = Series([True, True, True], dtype=np.bool_)
    tm.assert_series_equal(result, expected)
    result = s.str.contains('foo', na='foo')
    expected = Series(['foo', 'foo', 'foo'], dtype=np.object_)
    tm.assert_series_equal(result, expected)
    result = s.str.contains('foo')
    expected = Series([np.nan, np.nan, np.nan], dtype=np.object_)
    tm.assert_series_equal(result, expected)