def test_comparison_tuples(self):
    s = Series([(1, 1), (1, 2)])
    result = s == (1, 2)
    expected = Series([False, True])
    tm.assert_series_equal(result, expected)
    result = s != (1, 2)
    expected = Series([True, False])
    tm.assert_series_equal(result, expected)
    result = s == (0, 0)
    expected = Series([False, False])
    tm.assert_series_equal(result, expected)
    result = s != (0, 0)
    expected = Series([True, True])
    tm.assert_series_equal(result, expected)
    s = Series([(1, 1), (1, 1)])
    result = s == (1, 1)
    expected = Series([True, True])
    tm.assert_series_equal(result, expected)
    result = s != (1, 1)
    expected = Series([False, False])
    tm.assert_series_equal(result, expected)
    s = Series([frozenset([1]), frozenset([1, 2])])
    result = s == frozenset([1])
    expected = Series([True, False])
    tm.assert_series_equal(result, expected)