def test_astype_assignment(self):
    df_orig = DataFrame([['1', '2', '3', '.4', 5, 6.0, 'foo']], columns=list('ABCDEFG'))
    df = df_orig.copy()
    df.iloc[:, 0:2] = df.iloc[:, 0:2].astype(np.int64)
    expected = DataFrame([[1, 2, '3', '.4', 5, 6.0, 'foo']], columns=list('ABCDEFG'))
    tm.assert_frame_equal(df, expected)
    df = df_orig.copy()
    df.iloc[:, 0:2] = df.iloc[:, 0:2]._convert(datetime=True, numeric=True)
    expected = DataFrame([[1, 2, '3', '.4', 5, 6.0, 'foo']], columns=list('ABCDEFG'))
    tm.assert_frame_equal(df, expected)
    df = df_orig.copy()
    df.loc[:, 'A'] = df.loc[:, 'A'].astype(np.int64)
    expected = DataFrame([[1, '2', '3', '.4', 5, 6.0, 'foo']], columns=list('ABCDEFG'))
    tm.assert_frame_equal(df, expected)
    df = df_orig.copy()
    df.loc[:, ['B', 'C']] = df.loc[:, ['B', 'C']].astype(np.int64)
    expected = DataFrame([['1', 2, 3, '.4', 5, 6.0, 'foo']], columns=list('ABCDEFG'))
    tm.assert_frame_equal(df, expected)
    df = DataFrame({'A': [1.0, 2.0, 3.0, 4.0]})
    df.iloc[:, 0] = df['A'].astype(np.int64)
    expected = DataFrame({'A': [1, 2, 3, 4]})
    tm.assert_frame_equal(df, expected)
    df = DataFrame({'A': [1.0, 2.0, 3.0, 4.0]})
    df.loc[:, 'A'] = df['A'].astype(np.int64)
    expected = DataFrame({'A': [1, 2, 3, 4]})
    tm.assert_frame_equal(df, expected)