def test_astype_conversion(self):
    idx = PeriodIndex(['2016-05-16', 'NaT', NaT, np.NaN], freq='D')
    result = idx.astype(object)
    expected = Index([Period('2016-05-16', freq='D')] + [Period(NaT, freq='D')] * 3, dtype='object')
    tm.assert_index_equal(result, expected)
    result = idx.astype(np.int64)
    expected = Int64Index([16937] + [-9223372036854775808] * 3, dtype=np.int64)
    tm.assert_index_equal(result, expected)
    result = idx.astype(str)
    expected = Index((str(x) for x in idx))
    tm.assert_index_equal(result, expected)
    idx = period_range('1990', '2009', freq='A')
    result = idx.astype('i8')
    tm.assert_index_equal(result, Index(idx.asi8))
    tm.assert_numpy_array_equal(result.values, idx.asi8)