def test_count(self):
    values = np.array(['foo', 'foofoo', np.nan, 'foooofooofommmfoo'], dtype=np.object_)
    result = strings.str_count(values, 'f[o]+')
    exp = np.array([1, 2, np.nan, 4])
    tm.assert_numpy_array_equal(result, exp)
    result = Series(values).str.count('f[o]+')
    exp = Series([1, 2, np.nan, 4])
    assert isinstance(result, Series)
    tm.assert_series_equal(result, exp)
    mixed = np.array(['a', np.nan, 'b', True, datetime.today(), 'foo', None, 1, 2.0], dtype=object)
    rs = strings.str_count(mixed, 'a')
    xp = np.array([1, np.nan, 0, np.nan, np.nan, 0, np.nan, np.nan, np.nan])
    tm.assert_numpy_array_equal(rs, xp)
    rs = Series(mixed).str.count('a')
    xp = Series([1, np.nan, 0, np.nan, np.nan, 0, np.nan, np.nan, np.nan])
    assert isinstance(rs, Series)
    tm.assert_series_equal(rs, xp)