def test_diff_tz(self):
    ts = tm.makeTimeSeries(name='ts')
    ts.diff()
    result = ts.diff(-1)
    expected = ts - ts.shift(-1)
    tm.assert_series_equal(result, expected)
    result = ts.diff(0)
    expected = ts - ts
    tm.assert_series_equal(result, expected)
    s = Series(date_range('20130102', periods=5))
    result = s.diff()
    expected = s - s.shift(1)
    tm.assert_series_equal(result, expected)
    result = result - result.shift(1)
    expected = expected.diff()
    tm.assert_series_equal(result, expected)
    s = Series(date_range('2000-01-01 09:00:00', periods=5, tz='US/Eastern'), name='foo')
    result = s.diff()
    expected = Series(TimedeltaIndex(['NaT'] + ['1 days'] * 4), name='foo')
    tm.assert_series_equal(result, expected)