def test_contains_moar(self):
    s = Series(['A', 'B', 'C', 'Aaba', 'Baca', '', np.nan, 'CABA', 'dog', 'cat'])
    result = s.str.contains('a')
    expected = Series([False, False, False, True, True, False, np.nan, False, False, True])
    tm.assert_series_equal(result, expected)
    result = s.str.contains('a', case=False)
    expected = Series([True, False, False, True, True, False, np.nan, True, False, True])
    tm.assert_series_equal(result, expected)
    result = s.str.contains('Aa')
    expected = Series([False, False, False, True, False, False, np.nan, False, False, False])
    tm.assert_series_equal(result, expected)
    result = s.str.contains('ba')
    expected = Series([False, False, False, True, False, False, np.nan, False, False, False])
    tm.assert_series_equal(result, expected)
    result = s.str.contains('ba', case=False)
    expected = Series([False, False, False, True, True, False, np.nan, True, False, False])
    tm.assert_series_equal(result, expected)