@pytest.mark.parametrize('kwargs', [dict(), dict(other=None)])
def test_df_where_with_category(self, kwargs):
    df = DataFrame(np.arange(2 * 3).reshape(2, 3), columns=list('ABC'))
    mask = np.array([[True, False, True], [False, True, True]])
    df.A = df.A.astype('category')
    df.B = df.B.astype('category')
    df.C = df.C.astype('category')
    result = df.A.where(mask[:, 0], **kwargs)
    expected = Series(pd.Categorical([0, np.nan], categories=[0, 3]), name='A')
    tm.assert_series_equal(result, expected)