def test_find_nan(self):
    values = Series(['ABCDEFG', np.nan, 'DEFGHIJEF', np.nan, 'XXXX'])
    result = values.str.find('EF')
    tm.assert_series_equal(result, Series([4, np.nan, 1, np.nan, -1]))
    result = values.str.rfind('EF')
    tm.assert_series_equal(result, Series([4, np.nan, 7, np.nan, -1]))
    result = values.str.find('EF', 3)
    tm.assert_series_equal(result, Series([4, np.nan, 7, np.nan, -1]))
    result = values.str.rfind('EF', 3)
    tm.assert_series_equal(result, Series([4, np.nan, 7, np.nan, -1]))
    result = values.str.find('EF', 3, 6)
    tm.assert_series_equal(result, Series([4, np.nan, -1, np.nan, -1]))
    result = values.str.rfind('EF', 3, 6)
    tm.assert_series_equal(result, Series([4, np.nan, -1, np.nan, -1]))