def test_dtype_conversion(self):
    expected = self.read_csv(self.csv15)
    expected['byte_'] = expected['byte_'].astype(np.int8)
    expected['int_'] = expected['int_'].astype(np.int16)
    expected['long_'] = expected['long_'].astype(np.int32)
    expected['float_'] = expected['float_'].astype(np.float32)
    expected['double_'] = expected['double_'].astype(np.float64)
    expected['date_td'] = expected['date_td'].apply(datetime.strptime, args=('%Y-%m-%d',))
    no_conversion = read_stata(self.dta15_117, convert_dates=True)
    tm.assert_frame_equal(expected, no_conversion)
    conversion = read_stata(self.dta15_117, convert_dates=True, preserve_dtypes=False)
    expected = self.read_csv(self.csv15)
    expected['date_td'] = expected['date_td'].apply(datetime.strptime, args=('%Y-%m-%d',))
    tm.assert_frame_equal(expected, conversion)