def test_arith_ops_df_compat(self):
    s1 = pd.Series([1, 2, 3], index=list('ABC'), name='x')
    s2 = pd.Series([2, 2, 2], index=list('ABD'), name='x')
    exp = pd.Series([3.0, 4.0, np.nan, np.nan], index=list('ABCD'), name='x')
    tm.assert_series_equal(s1 + s2, exp)
    tm.assert_series_equal(s2 + s1, exp)
    exp = pd.DataFrame({'x': [3.0, 4.0, np.nan, np.nan]}, index=list('ABCD'))
    tm.assert_frame_equal(s1.to_frame() + s2.to_frame(), exp)
    tm.assert_frame_equal(s2.to_frame() + s1.to_frame(), exp)
    s3 = pd.Series([1, 2, 3], index=list('ABC'), name='x')
    s4 = pd.Series([2, 2, 2, 2], index=list('ABCD'), name='x')
    exp = pd.Series([3, 4, 5, np.nan], index=list('ABCD'), name='x')
    tm.assert_series_equal(s3 + s4, exp)
    tm.assert_series_equal(s4 + s3, exp)
    exp = pd.DataFrame({'x': [3, 4, 5, np.nan]}, index=list('ABCD'))
    tm.assert_frame_equal(s3.to_frame() + s4.to_frame(), exp)
    tm.assert_frame_equal(s4.to_frame() + s3.to_frame(), exp)