def test_matmul(self):
    a = DataFrame(np.random.randn(3, 4), index=['a', 'b', 'c'], columns=['p', 'q', 'r', 's'])
    b = DataFrame(np.random.randn(4, 2), index=['p', 'q', 'r', 's'], columns=['one', 'two'])
    result = operator.matmul(a, b)
    expected = DataFrame(np.dot(a.values, b.values), index=['a', 'b', 'c'], columns=['one', 'two'])
    tm.assert_frame_equal(result, expected)
    result = operator.matmul(a, b.one)
    expected = Series(np.dot(a.values, b.one.values), index=['a', 'b', 'c'])
    tm.assert_series_equal(result, expected)
    result = operator.matmul(a.values, b)
    assert isinstance(result, DataFrame)
    assert result.columns.equals(b.columns)
    assert result.index.equals(pd.Index(range(3)))
    expected = np.dot(a.values, b.values)
    tm.assert_almost_equal(result.values, expected)
    result = operator.matmul(a.values.tolist(), b)
    expected = DataFrame(np.dot(a.values, b.values), index=['a', 'b', 'c'], columns=['one', 'two'])
    tm.assert_almost_equal(result.values, expected.values)
    a['q'] = a.q.round().astype(int)
    result = operator.matmul(a, b)
    expected = DataFrame(np.dot(a.values, b.values), index=['a', 'b', 'c'], columns=['one', 'two'])
    tm.assert_frame_equal(result, expected)
    a = a.astype(int)
    result = operator.matmul(a, b)
    expected = DataFrame(np.dot(a.values, b.values), index=['a', 'b', 'c'], columns=['one', 'two'])
    tm.assert_frame_equal(result, expected)
    df = DataFrame(np.random.randn(3, 4), index=[1, 2, 3], columns=range(4))
    df2 = DataFrame(np.random.randn(5, 3), index=range(5), columns=[1, 2, 3])
    with pytest.raises(ValueError, match='aligned'):
        operator.matmul(df, df2)