@pytest.mark.slow
def test_subplots_layout(self):
    df = DataFrame(np.random.rand(10, 3), index=list(string.ascii_letters[:10]))
    axes = df.plot(subplots=True, layout=(2, 2))
    self._check_axes_shape(axes, axes_num=3, layout=(2, 2))
    assert axes.shape == (2, 2)
    axes = df.plot(subplots=True, layout=(-1, 2))
    self._check_axes_shape(axes, axes_num=3, layout=(2, 2))
    assert axes.shape == (2, 2)
    axes = df.plot(subplots=True, layout=(2, -1))
    self._check_axes_shape(axes, axes_num=3, layout=(2, 2))
    assert axes.shape == (2, 2)
    axes = df.plot(subplots=True, layout=(1, 4))
    self._check_axes_shape(axes, axes_num=3, layout=(1, 4))
    assert axes.shape == (1, 4)
    axes = df.plot(subplots=True, layout=(-1, 4))
    self._check_axes_shape(axes, axes_num=3, layout=(1, 4))
    assert axes.shape == (1, 4)
    axes = df.plot(subplots=True, layout=(4, -1))
    self._check_axes_shape(axes, axes_num=3, layout=(4, 1))
    assert axes.shape == (4, 1)
    with pytest.raises(ValueError):
        df.plot(subplots=True, layout=(1, 1))
    with pytest.raises(ValueError):
        df.plot(subplots=True, layout=(-1, -1))
    df = DataFrame(np.random.rand(10, 1), index=list(string.ascii_letters[:10]))
    axes = df.plot(subplots=True)
    self._check_axes_shape(axes, axes_num=1, layout=(1, 1))
    assert axes.shape == (1,)
    axes = df.plot(subplots=True, layout=(3, 3))
    self._check_axes_shape(axes, axes_num=1, layout=(3, 3))
    assert axes.shape == (3, 3)