def test_value_counts_categorical_not_ordered(self):
    values = pd.Categorical([1, 2, 3, 1, 1, 3], ordered=False)
    exp_idx = pd.CategoricalIndex([1, 3, 2], categories=[1, 2, 3], ordered=False)
    exp = pd.Series([3, 2, 1], index=exp_idx, name='xxx')
    ser = pd.Series(values, name='xxx')
    tm.assert_series_equal(ser.value_counts(), exp)
    idx = pd.CategoricalIndex(values, name='xxx')
    tm.assert_series_equal(idx.value_counts(), exp)
    exp = pd.Series(np.array([3.0, 2.0, 1]) / 6.0, index=exp_idx, name='xxx')
    tm.assert_series_equal(ser.value_counts(normalize=True), exp)
    tm.assert_series_equal(idx.value_counts(normalize=True), exp)