def test_basic(self):
    codes, uniques = algos.factorize(['a', 'b', 'b', 'a', 'a', 'c', 'c', 'c'])
    tm.assert_numpy_array_equal(uniques, np.array(['a', 'b', 'c'], dtype=object))
    codes, uniques = algos.factorize(['a', 'b', 'b', 'a', 'a', 'c', 'c', 'c'], sort=True)
    exp = np.array([0, 1, 1, 0, 0, 2, 2, 2], dtype=np.intp)
    tm.assert_numpy_array_equal(codes, exp)
    exp = np.array(['a', 'b', 'c'], dtype=object)
    tm.assert_numpy_array_equal(uniques, exp)
    codes, uniques = algos.factorize(list(reversed(range(5))))
    exp = np.array([0, 1, 2, 3, 4], dtype=np.intp)
    tm.assert_numpy_array_equal(codes, exp)
    exp = np.array([4, 3, 2, 1, 0], dtype=np.int64)
    tm.assert_numpy_array_equal(uniques, exp)
    codes, uniques = algos.factorize(list(reversed(range(5))), sort=True)
    exp = np.array([4, 3, 2, 1, 0], dtype=np.intp)
    tm.assert_numpy_array_equal(codes, exp)
    exp = np.array([0, 1, 2, 3, 4], dtype=np.int64)
    tm.assert_numpy_array_equal(uniques, exp)
    codes, uniques = algos.factorize(list(reversed(np.arange(5.0))))
    exp = np.array([0, 1, 2, 3, 4], dtype=np.intp)
    tm.assert_numpy_array_equal(codes, exp)
    exp = np.array([4.0, 3.0, 2.0, 1.0, 0.0], dtype=np.float64)
    tm.assert_numpy_array_equal(uniques, exp)
    codes, uniques = algos.factorize(list(reversed(np.arange(5.0))), sort=True)
    exp = np.array([4, 3, 2, 1, 0], dtype=np.intp)
    tm.assert_numpy_array_equal(codes, exp)
    exp = np.array([0.0, 1.0, 2.0, 3.0, 4.0], dtype=np.float64)
    tm.assert_numpy_array_equal(uniques, exp)