def test_astype_datetime64tz(self):
    s = Series(date_range('20130101', periods=3, tz='US/Eastern'))
    result = s.astype(object)
    expected = Series(s.astype(object), dtype=object)
    tm.assert_series_equal(result, expected)
    result = Series(s.values).dt.tz_localize('UTC').dt.tz_convert(s.dt.tz)
    tm.assert_series_equal(result, s)
    result = Series(s.astype(object))
    expected = s.astype(object)
    tm.assert_series_equal(result, expected)
    result = Series(s.values).astype('datetime64[ns, US/Eastern]')
    tm.assert_series_equal(result, s)
    result = Series(s.values).astype(s.dtype)
    tm.assert_series_equal(result, s)
    result = s.astype('datetime64[ns, CET]')
    expected = Series(date_range('20130101 06:00:00', periods=3, tz='CET'))
    tm.assert_series_equal(result, expected)