@pytest.mark.parametrize('data, names', [([], (None,)), ([], ('i1',)), ([], (None, 'i2')), ([], ('i1', 'i2')), (['a3', 'b3', 'd4c2'], (None,)), (['a3', 'b3', 'd4c2'], ('i1', 'i2')), (['a3', 'b3', 'd4c2'], (None, 'i2')), (['a3', 'b3', 'd4c2'], ('i1', 'i2'))])
def test_extractall_no_matches(self, data, names):
    n = len(data)
    if len(names) == 1:
        i = Index(range(n), name=names[0])
    else:
        a = (tuple([i] * (n - 1)) for i in range(n))
        i = MultiIndex.from_tuples(a, names=names)
    s = Series(data, name='series_name', index=i, dtype='object')
    ei = MultiIndex.from_tuples([], names=names + ('match',))
    r = s.str.extractall('(z)')
    e = DataFrame(columns=[0], index=ei)
    tm.assert_frame_equal(r, e)
    r = s.str.extractall('(z)(z)')
    e = DataFrame(columns=[0, 1], index=ei)
    tm.assert_frame_equal(r, e)
    r = s.str.extractall('(?P<first>z)')
    e = DataFrame(columns=['first'], index=ei)
    tm.assert_frame_equal(r, e)
    r = s.str.extractall('(?P<first>z)(?P<second>z)')
    e = DataFrame(columns=['first', 'second'], index=ei)
    tm.assert_frame_equal(r, e)
    r = s.str.extractall('(z)(?P<second>z)')
    e = DataFrame(columns=[0, 'second'], index=ei)
    tm.assert_frame_equal(r, e)