@property
def inferred_freq(self):
    """
        Tryies to return a string representing a frequency guess,
        generated by infer_freq.  Returns None if it can't autodetect the
        frequency.
        """
    if self.ndim != 1:
        return None
    try:
        return frequencies.infer_freq(self)
    except ValueError:
        return None