def test_unique_ordered(self):
    cat = Categorical(['b', 'a', 'b'], categories=['a', 'b'], ordered=True)
    res = cat.unique()
    exp_cat = Categorical(['b', 'a'], categories=['a', 'b'], ordered=True)
    tm.assert_categorical_equal(res, exp_cat)
    cat = Categorical(['c', 'b', 'a', 'a'], categories=['a', 'b', 'c'], ordered=True)
    res = cat.unique()
    exp_cat = Categorical(['c', 'b', 'a'], categories=['a', 'b', 'c'], ordered=True)
    tm.assert_categorical_equal(res, exp_cat)
    cat = Categorical(['b', 'a', 'a'], categories=['a', 'b', 'c'], ordered=True)
    res = cat.unique()
    exp_cat = Categorical(['b', 'a'], categories=['a', 'b'], ordered=True)
    tm.assert_categorical_equal(res, exp_cat)
    cat = Categorical(['b', 'b', np.nan, 'a'], categories=['a', 'b', 'c'], ordered=True)
    res = cat.unique()
    exp_cat = Categorical(['b', np.nan, 'a'], categories=['a', 'b'], ordered=True)
    tm.assert_categorical_equal(res, exp_cat)