def test_timedelta_other_units(self):
    idx = pd.TimedeltaIndex(['1 days', 'NaT', '2 days'])
    exp = np.array([False, True, False])
    tm.assert_numpy_array_equal(isna(idx), exp)
    tm.assert_numpy_array_equal(notna(idx), ~exp)
    tm.assert_numpy_array_equal(isna(idx.values), exp)
    tm.assert_numpy_array_equal(notna(idx.values), ~exp)
    for dtype in ['timedelta64[D]', 'timedelta64[h]', 'timedelta64[m]', 'timedelta64[s]', 'timedelta64[ms]', 'timedelta64[us]', 'timedelta64[ns]']:
        values = idx.values.astype(dtype)
        exp = np.array([False, True, False])
        tm.assert_numpy_array_equal(isna(values), exp)
        tm.assert_numpy_array_equal(notna(values), ~exp)
        exp = pd.Series([False, True, False])
        s = pd.Series(values)
        tm.assert_series_equal(isna(s), exp)
        tm.assert_series_equal(notna(s), ~exp)
        s = pd.Series(values, dtype=object)
        tm.assert_series_equal(isna(s), exp)
        tm.assert_series_equal(notna(s), ~exp)