def test_apply_mixed_dtype_corner(self):
    df = DataFrame({'A': ['foo'], 'B': [1.0]})
    result = df[:0].apply(np.mean, axis=1)
    expected = Series(np.nan, index=pd.Index([], dtype='int64'))
    tm.assert_series_equal(result, expected)
    df = DataFrame({'A': ['foo'], 'B': [1.0]})
    result = df.apply(lambda x: x['A'], axis=1)
    expected = Series(['foo'], index=[0])
    tm.assert_series_equal(result, expected)
    result = df.apply(lambda x: x['B'], axis=1)
    expected = Series([1.0], index=[0])
    tm.assert_series_equal(result, expected)