def test_center_ljust_rjust(self):
    values = Series(['a', 'b', np.nan, 'c', np.nan, 'eeeeee'])
    result = values.str.center(5)
    exp = Series(['  a  ', '  b  ', np.nan, '  c  ', np.nan, 'eeeeee'])
    tm.assert_almost_equal(result, exp)
    result = values.str.ljust(5)
    exp = Series(['a    ', 'b    ', np.nan, 'c    ', np.nan, 'eeeeee'])
    tm.assert_almost_equal(result, exp)
    result = values.str.rjust(5)
    exp = Series(['    a', '    b', np.nan, '    c', np.nan, 'eeeeee'])
    tm.assert_almost_equal(result, exp)
    mixed = Series(['a', np.nan, 'b', True, datetime.today(), 'c', 'eee', None, 1, 2.0])
    rs = Series(mixed).str.center(5)
    xp = Series(['  a  ', np.nan, '  b  ', np.nan, np.nan, '  c  ', ' eee ', np.nan, np.nan, np.nan])
    assert isinstance(rs, Series)
    tm.assert_almost_equal(rs, xp)
    rs = Series(mixed).str.ljust(5)
    xp = Series(['a    ', np.nan, 'b    ', np.nan, np.nan, 'c    ', 'eee  ', np.nan, np.nan, np.nan])
    assert isinstance(rs, Series)
    tm.assert_almost_equal(rs, xp)
    rs = Series(mixed).str.rjust(5)
    xp = Series(['    a', np.nan, '    b', np.nan, np.nan, '    c', '  eee', np.nan, np.nan, np.nan])
    assert isinstance(rs, Series)
    tm.assert_almost_equal(rs, xp)