def test_grouper_creation_bug(self):
    df = DataFrame({'A': [0, 0, 1, 1, 2, 2], 'B': [1, 2, 3, 4, 5, 6]})
    g = df.groupby('A')
    expected = g.sum()
    g = df.groupby(pd.Grouper(key='A'))
    result = g.sum()
    tm.assert_frame_equal(result, expected)
    result = g.apply(lambda x: x.sum())
    tm.assert_frame_equal(result, expected)
    g = df.groupby(pd.Grouper(key='A', axis=0))
    result = g.sum()
    tm.assert_frame_equal(result, expected)
    df = DataFrame({'A': [0, 0, 0, 1, 1, 1], 'B': [1, 1, 2, 2, 3, 3], 'C': [1, 2, 3, 4, 5, 6]})
    expected = df.groupby('A').sum()
    g = df.groupby([pd.Grouper(key='A')])
    result = g.sum()
    tm.assert_frame_equal(result, expected)
    expected = df.groupby(['A', 'B']).sum()
    g = df.groupby([pd.Grouper(key='A'), pd.Grouper(key='B')])
    result = g.sum()
    tm.assert_frame_equal(result, expected)
    g = df.groupby(['A', pd.Grouper(key='B')])
    result = g.sum()
    tm.assert_frame_equal(result, expected)
    g = df.groupby([pd.Grouper(key='A'), 'B'])
    result = g.sum()
    tm.assert_frame_equal(result, expected)
    s = Series(np.arange(8, dtype='int64'), index=pd.MultiIndex.from_product([list('ab'), range(2), date_range('20130101', periods=2)], names=['one', 'two', 'three']))
    result = s.groupby(pd.Grouper(level='three', freq='M')).sum()
    expected = Series([28], index=Index([Timestamp('2013-01-31')], freq='M', name='three'))
    tm.assert_series_equal(result, expected)
    result = s.groupby(pd.Grouper(level='one')).sum()
    expected = s.groupby(level='one').sum()
    tm.assert_series_equal(result, expected)