def test_logical_ops_bool_dtype_with_ndarray(self):
    left = pd.Series([True, True, True, False, True])
    right = [True, False, None, True, np.nan]
    expected = pd.Series([True, False, False, False, False])
    result = left & right
    tm.assert_series_equal(result, expected)
    result = left & np.array(right)
    tm.assert_series_equal(result, expected)
    result = left & pd.Index(right)
    tm.assert_series_equal(result, expected)
    result = left & pd.Series(right)
    tm.assert_series_equal(result, expected)
    expected = pd.Series([True, True, True, True, True])
    result = left | right
    tm.assert_series_equal(result, expected)
    result = left | np.array(right)
    tm.assert_series_equal(result, expected)
    result = left | pd.Index(right)
    tm.assert_series_equal(result, expected)
    result = left | pd.Series(right)
    tm.assert_series_equal(result, expected)
    expected = pd.Series([False, True, True, True, True])
    result = left ^ right
    tm.assert_series_equal(result, expected)
    result = left ^ np.array(right)
    tm.assert_series_equal(result, expected)
    result = left ^ pd.Index(right)
    tm.assert_series_equal(result, expected)
    result = left ^ pd.Series(right)
    tm.assert_series_equal(result, expected)