def test_replace_compiled_regex(self):
    values = Series(['fooBAD__barBAD', np.nan])
    pat = re.compile('BAD[_]*')
    result = values.str.replace(pat, '')
    exp = Series(['foobar', np.nan])
    tm.assert_series_equal(result, exp)
    result = values.str.replace(pat, '', n=1)
    exp = Series(['foobarBAD', np.nan])
    tm.assert_series_equal(result, exp)
    mixed = Series(['aBAD', np.nan, 'bBAD', True, datetime.today(), 'fooBAD', None, 1, 2.0])
    rs = Series(mixed).str.replace(pat, '')
    xp = Series(['a', np.nan, 'b', np.nan, np.nan, 'foo', np.nan, np.nan, np.nan])
    assert isinstance(rs, Series)
    tm.assert_almost_equal(rs, xp)
    values = Series([b'abcd,\xc3\xa0'.decode('utf-8')])
    exp = Series([b'abcd, \xc3\xa0'.decode('utf-8')])
    pat = re.compile('(?<=\\w),(?=\\w)', flags=re.UNICODE)
    result = values.str.replace(pat, ', ')
    tm.assert_series_equal(result, exp)
    values = Series(['fooBAD__barBAD__bad', np.nan])
    pat = re.compile('BAD[_]*')
    with pytest.raises(ValueError, match='case and flags cannot be'):
        result = values.str.replace(pat, '', flags=re.IGNORECASE)
    with pytest.raises(ValueError, match='case and flags cannot be'):
        result = values.str.replace(pat, '', case=False)
    with pytest.raises(ValueError, match='case and flags cannot be'):
        result = values.str.replace(pat, '', case=True)
    values = Series(['fooBAD__barBAD', np.nan])
    repl = lambda m: m.group(0).swapcase()
    pat = re.compile('[a-z][A-Z]{2}')
    result = values.str.replace(pat, repl, n=2)
    exp = Series(['foObaD__baRbaD', np.nan])
    tm.assert_series_equal(result, exp)