@pytest.mark.parametrize('left,right', [('lt', 'gt'), ('le', 'ge'), ('eq', 'eq'), ('ne', 'ne')])
def test_timestamp_compare_series(self, left, right):
    ser = pd.Series(pd.date_range('20010101', periods=10), name='dates')
    s_nat = ser.copy(deep=True)
    ser[0] = pd.Timestamp('nat')
    ser[3] = pd.Timestamp('nat')
    left_f = getattr(operator, left)
    right_f = getattr(operator, right)
    expected = left_f(ser, pd.Timestamp('20010109'))
    result = right_f(pd.Timestamp('20010109'), ser)
    tm.assert_series_equal(result, expected)
    expected = left_f(ser, pd.Timestamp('nat'))
    result = right_f(pd.Timestamp('nat'), ser)
    tm.assert_series_equal(result, expected)
    expected = left_f(s_nat, pd.Timestamp('20010109'))
    result = right_f(pd.Timestamp('20010109'), s_nat)
    tm.assert_series_equal(result, expected)
    expected = left_f(s_nat, pd.Timestamp('nat'))
    result = right_f(pd.Timestamp('nat'), s_nat)
    tm.assert_series_equal(result, expected)