def test_read_only_source(self):
    rw_array = np.eye(10)
    rw_df = DataFrame(rw_array)
    ro_array = np.eye(10)
    ro_array.setflags(write=False)
    ro_df = DataFrame(ro_array)
    tm.assert_frame_equal(rw_df.iloc[[1, 2, 3]], ro_df.iloc[[1, 2, 3]])
    tm.assert_frame_equal(rw_df.iloc[[1]], ro_df.iloc[[1]])
    tm.assert_series_equal(rw_df.iloc[1], ro_df.iloc[1])
    tm.assert_frame_equal(rw_df.iloc[1:3], ro_df.iloc[1:3])
    tm.assert_frame_equal(rw_df.loc[[1, 2, 3]], ro_df.loc[[1, 2, 3]])
    tm.assert_frame_equal(rw_df.loc[[1]], ro_df.loc[[1]])
    tm.assert_series_equal(rw_df.loc[1], ro_df.loc[1])
    tm.assert_frame_equal(rw_df.loc[1:3], ro_df.loc[1:3])