def test_to_csv_from_csv_categorical(self):
    s = Series(pd.Categorical(['a', 'b', 'b', 'a', 'a', 'c', 'c', 'c']))
    s2 = Series(['a', 'b', 'b', 'a', 'a', 'c', 'c', 'c'])
    res = StringIO()
    s.to_csv(res, header=False)
    exp = StringIO()
    s2.to_csv(exp, header=False)
    assert res.getvalue() == exp.getvalue()
    df = DataFrame({'s': s})
    df2 = DataFrame({'s': s2})
    res = StringIO()
    df.to_csv(res)
    exp = StringIO()
    df2.to_csv(exp)
    assert res.getvalue() == exp.getvalue()