def test_mixed_array_comparison(self, kind):
    rdtype = 'int64'
    values = self._base([np.nan, 1, 2, 0, np.nan, 0, 1, 2, 1, np.nan])
    rvalues = self._base([2, 0, 2, 3, 0, 0, 1, 5, 2, 0], dtype=rdtype)
    a = self._klass(values, kind=kind)
    b = self._klass(rvalues, kind=kind)
    assert b.dtype == SparseDtype(rdtype)
    self._check_comparison_ops(a, b, values, rvalues)
    self._check_comparison_ops(a, b * 0, values, rvalues * 0)
    a = self._klass(values, kind=kind, fill_value=0)
    b = self._klass(rvalues, kind=kind)
    assert b.dtype == SparseDtype(rdtype)
    self._check_comparison_ops(a, b, values, rvalues)
    a = self._klass(values, kind=kind, fill_value=0)
    b = self._klass(rvalues, kind=kind, fill_value=0)
    assert b.dtype == SparseDtype(rdtype)
    self._check_comparison_ops(a, b, values, rvalues)
    a = self._klass(values, kind=kind, fill_value=1)
    b = self._klass(rvalues, kind=kind, fill_value=2)
    assert b.dtype == SparseDtype(rdtype, fill_value=2)
    self._check_comparison_ops(a, b, values, rvalues)