def test_is_datetime_dtypes(self):
    ts = pd.date_range('20130101', periods=3)
    tsa = pd.date_range('20130101', periods=3, tz='US/Eastern')
    assert is_datetime64_dtype('datetime64')
    assert is_datetime64_dtype('datetime64[ns]')
    assert is_datetime64_dtype(ts)
    assert not is_datetime64_dtype(tsa)
    assert not is_datetime64_ns_dtype('datetime64')
    assert is_datetime64_ns_dtype('datetime64[ns]')
    assert is_datetime64_ns_dtype(ts)
    assert is_datetime64_ns_dtype(tsa)
    assert is_datetime64_any_dtype('datetime64')
    assert is_datetime64_any_dtype('datetime64[ns]')
    assert is_datetime64_any_dtype(ts)
    assert is_datetime64_any_dtype(tsa)
    assert not is_datetime64tz_dtype('datetime64')
    assert not is_datetime64tz_dtype('datetime64[ns]')
    assert not is_datetime64tz_dtype(ts)
    assert is_datetime64tz_dtype(tsa)
    for tz in ['US/Eastern', 'UTC']:
        dtype = f'datetime64[ns, {tz}]'
        assert not is_datetime64_dtype(dtype)
        assert is_datetime64tz_dtype(dtype)
        assert is_datetime64_ns_dtype(dtype)
        assert is_datetime64_any_dtype(dtype)