def test1_index(self):
    data_csv = pd.read_csv(self.file01.replace('.xpt', '.csv'))
    data_csv = data_csv.set_index('SEQN')
    numeric_as_float(data_csv)
    data = read_sas(self.file01, index='SEQN', format='xport')
    tm.assert_frame_equal(data, data_csv, check_index_type=False)
    reader = read_sas(self.file01, index='SEQN', format='xport', iterator=True)
    data = reader.read(10)
    reader.close()
    tm.assert_frame_equal(data, data_csv.iloc[0:10, :], check_index_type=False)
    reader = read_sas(self.file01, index='SEQN', format='xport', chunksize=10)
    data = reader.get_chunk()
    reader.close()
    tm.assert_frame_equal(data, data_csv.iloc[0:10, :], check_index_type=False)