def test_append_tz_explicit_pytz(self):
    from pytz import timezone as timezone
    rng = date_range('5/8/2012 1:45', periods=10, freq='5T', tz=timezone('US/Eastern'))
    rng2 = date_range('5/8/2012 2:35', periods=10, freq='5T', tz=timezone('US/Eastern'))
    rng3 = date_range('5/8/2012 1:45', periods=20, freq='5T', tz=timezone('US/Eastern'))
    ts = Series(np.random.randn(len(rng)), rng)
    df = DataFrame(np.random.randn(len(rng), 4), index=rng)
    ts2 = Series(np.random.randn(len(rng2)), rng2)
    df2 = DataFrame(np.random.randn(len(rng2), 4), index=rng2)
    result = ts.append(ts2)
    result_df = df.append(df2)
    tm.assert_index_equal(result.index, rng3)
    tm.assert_index_equal(result_df.index, rng3)
    appended = rng.append(rng2)
    tm.assert_index_equal(appended, rng3)