def test_concat_categorical(self):
    s1 = pd.Series([1, 2, np.nan], dtype='category')
    s2 = pd.Series([2, 1, 2], dtype='category')
    exp = pd.Series([1, 2, np.nan, 2, 1, 2], dtype='category')
    tm.assert_series_equal(pd.concat([s1, s2], ignore_index=True), exp)
    tm.assert_series_equal(s1.append(s2, ignore_index=True), exp)
    s1 = pd.Series([3, 2], dtype='category')
    s2 = pd.Series([2, 1], dtype='category')
    exp = pd.Series([3, 2, 2, 1])
    tm.assert_series_equal(pd.concat([s1, s2], ignore_index=True), exp)
    tm.assert_series_equal(s1.append(s2, ignore_index=True), exp)
    s1 = pd.Series([10, 11, np.nan], dtype='category')
    s2 = pd.Series([np.nan, 1, 3, 2], dtype='category')
    exp = pd.Series([10, 11, np.nan, np.nan, 1, 3, 2], dtype='object')
    tm.assert_series_equal(pd.concat([s1, s2], ignore_index=True), exp)
    tm.assert_series_equal(s1.append(s2, ignore_index=True), exp)