def test_isna_lists(self):
    result = isna([[False]])
    exp = np.array([[False]])
    tm.assert_numpy_array_equal(result, exp)
    result = isna([[1], [2]])
    exp = np.array([[False], [False]])
    tm.assert_numpy_array_equal(result, exp)
    result = isna(['foo', 'bar'])
    exp = np.array([False, False])
    tm.assert_numpy_array_equal(result, exp)
    result = isna(['foo', 'bar'])
    exp = np.array([False, False])
    tm.assert_numpy_array_equal(result, exp)
    result = isna([np.NaN, 'world'])
    exp = np.array([True, False])
    tm.assert_numpy_array_equal(result, exp)