def test_ufunc(self):
    sparse = SparseArray([1, np.nan, 2, np.nan, -2])
    result = SparseArray([1, np.nan, 2, np.nan, 2])
    tm.assert_sp_array_equal(abs(sparse), result)
    tm.assert_sp_array_equal(np.abs(sparse), result)
    sparse = SparseArray([1, -1, 2, -2], fill_value=1)
    result = SparseArray([1, 2, 2], sparse_index=sparse.sp_index, fill_value=1)
    tm.assert_sp_array_equal(abs(sparse), result)
    tm.assert_sp_array_equal(np.abs(sparse), result)
    sparse = SparseArray([1, -1, 2, -2], fill_value=-1)
    result = SparseArray([1, 2, 2], sparse_index=sparse.sp_index, fill_value=1)
    tm.assert_sp_array_equal(abs(sparse), result)
    tm.assert_sp_array_equal(np.abs(sparse), result)
    sparse = SparseArray([1, np.nan, 2, np.nan, -2])
    result = SparseArray(np.sin([1, np.nan, 2, np.nan, -2]))
    tm.assert_sp_array_equal(np.sin(sparse), result)
    sparse = SparseArray([1, -1, 2, -2], fill_value=1)
    result = SparseArray(np.sin([1, -1, 2, -2]), fill_value=np.sin(1))
    tm.assert_sp_array_equal(np.sin(sparse), result)
    sparse = SparseArray([1, -1, 0, -2], fill_value=0)
    result = SparseArray(np.sin([1, -1, 0, -2]), fill_value=np.sin(0))
    tm.assert_sp_array_equal(np.sin(sparse), result)