def test_concat_categorical_coercion_nan(self):
    s1 = pd.Series(np.array([np.nan, np.nan], dtype=np.float64), dtype='category')
    s2 = pd.Series([np.nan, 1])
    exp = pd.Series([np.nan, np.nan, np.nan, 1])
    tm.assert_series_equal(pd.concat([s1, s2], ignore_index=True), exp)
    tm.assert_series_equal(s1.append(s2, ignore_index=True), exp)
    s1 = pd.Series([1, np.nan], dtype='category')
    s2 = pd.Series([np.nan, np.nan])
    exp = pd.Series([1, np.nan, np.nan, np.nan], dtype='object')
    tm.assert_series_equal(pd.concat([s1, s2], ignore_index=True), exp)
    tm.assert_series_equal(s1.append(s2, ignore_index=True), exp)
    s1 = pd.Series([np.nan, np.nan], dtype='category')
    s2 = pd.Series([np.nan, np.nan])
    exp = pd.Series([np.nan, np.nan, np.nan, np.nan])
    tm.assert_series_equal(pd.concat([s1, s2], ignore_index=True), exp)
    tm.assert_series_equal(s1.append(s2, ignore_index=True), exp)
    tm.assert_series_equal(pd.concat([s2, s1], ignore_index=True), exp)
    tm.assert_series_equal(s2.append(s1, ignore_index=True), exp)
    s1 = pd.Series([np.nan, np.nan], dtype='category')
    s2 = pd.Series([np.nan, np.nan], dtype='category')
    exp = pd.Series([np.nan, np.nan, np.nan, np.nan], dtype='category')
    tm.assert_series_equal(pd.concat([s1, s2], ignore_index=True), exp)
    tm.assert_series_equal(s1.append(s2, ignore_index=True), exp)