def test_factorize(self):
    idx1 = TimedeltaIndex(['1 day', '1 day', '2 day', '2 day', '3 day', '3 day'])
    exp_arr = np.array([0, 0, 1, 1, 2, 2], dtype=np.intp)
    exp_idx = TimedeltaIndex(['1 day', '2 day', '3 day'])
    arr, idx = idx1.factorize()
    tm.assert_numpy_array_equal(arr, exp_arr)
    tm.assert_index_equal(idx, exp_idx)
    arr, idx = idx1.factorize(sort=True)
    tm.assert_numpy_array_equal(arr, exp_arr)
    tm.assert_index_equal(idx, exp_idx)
    idx3 = timedelta_range('1 day', periods=4, freq='s')
    exp_arr = np.array([0, 1, 2, 3], dtype=np.intp)
    arr, idx = idx3.factorize()
    tm.assert_numpy_array_equal(arr, exp_arr)
    tm.assert_index_equal(idx, idx3)