def test_constructor_with_generator(self):
    exp = Categorical([0, 1, 2])
    cat = Categorical((x for x in [0, 1, 2]))
    tm.assert_categorical_equal(cat, exp)
    cat = Categorical(range(3))
    tm.assert_categorical_equal(cat, exp)
    MultiIndex.from_product([range(5), ['a', 'b', 'c']])
    cat = Categorical([0, 1, 2], categories=(x for x in [0, 1, 2]))
    tm.assert_categorical_equal(cat, exp)
    cat = Categorical([0, 1, 2], categories=range(3))
    tm.assert_categorical_equal(cat, exp)