def test_regex_replace_scalar_inplace(self, mix_ab):
    obj = {'a': list('ab..'), 'b': list('efgh')}
    dfobj = DataFrame(obj)
    dfmix = DataFrame(mix_ab)
    res = dfobj.copy()
    res.replace('\\s*\\.\\s*', np.nan, regex=True, inplace=True)
    tm.assert_frame_equal(dfobj, res.fillna('.'))
    res = dfmix.copy()
    res.replace('\\s*\\.\\s*', np.nan, regex=True, inplace=True)
    tm.assert_frame_equal(dfmix, res.fillna('.'))
    res = dfobj.copy()
    res.replace('\\s*(\\.)\\s*', '\\1\\1\\1', regex=True, inplace=True)
    objc = obj.copy()
    objc['a'] = ['a', 'b', '...', '...']
    expec = DataFrame(objc)
    tm.assert_frame_equal(res, expec)
    res = dfmix.copy()
    res.replace('\\s*(\\.)\\s*', '\\1\\1\\1', regex=True, inplace=True)
    mixc = mix_ab.copy()
    mixc['b'] = ['a', 'b', '...', '...']
    expec = DataFrame(mixc)
    tm.assert_frame_equal(res, expec)
    res = dfobj.copy()
    res.replace(re.compile('\\s*\\.\\s*'), np.nan, regex=True, inplace=True)
    tm.assert_frame_equal(dfobj, res.fillna('.'))
    res = dfmix.copy()
    res.replace(re.compile('\\s*\\.\\s*'), np.nan, regex=True, inplace=True)
    tm.assert_frame_equal(dfmix, res.fillna('.'))
    res = dfobj.copy()
    res.replace(re.compile('\\s*(\\.)\\s*'), '\\1\\1\\1', regex=True, inplace=True)
    objc = obj.copy()
    objc['a'] = ['a', 'b', '...', '...']
    expec = DataFrame(objc)
    tm.assert_frame_equal(res, expec)
    res = dfmix.copy()
    res.replace(re.compile('\\s*(\\.)\\s*'), '\\1\\1\\1', regex=True, inplace=True)
    mixc = mix_ab.copy()
    mixc['b'] = ['a', 'b', '...', '...']
    expec = DataFrame(mixc)
    tm.assert_frame_equal(res, expec)
    res = dfobj.copy()
    res.replace(regex='\\s*\\.\\s*', value=np.nan, inplace=True)
    tm.assert_frame_equal(dfobj, res.fillna('.'))
    res = dfmix.copy()
    res.replace(regex='\\s*\\.\\s*', value=np.nan, inplace=True)
    tm.assert_frame_equal(dfmix, res.fillna('.'))
    res = dfobj.copy()
    res.replace(regex='\\s*(\\.)\\s*', value='\\1\\1\\1', inplace=True)
    objc = obj.copy()
    objc['a'] = ['a', 'b', '...', '...']
    expec = DataFrame(objc)
    tm.assert_frame_equal(res, expec)
    res = dfmix.copy()
    res.replace(regex='\\s*(\\.)\\s*', value='\\1\\1\\1', inplace=True)
    mixc = mix_ab.copy()
    mixc['b'] = ['a', 'b', '...', '...']
    expec = DataFrame(mixc)
    tm.assert_frame_equal(res, expec)
    res = dfobj.copy()
    res.replace(regex=re.compile('\\s*\\.\\s*'), value=np.nan, inplace=True)
    tm.assert_frame_equal(dfobj, res.fillna('.'))
    res = dfmix.copy()
    res.replace(regex=re.compile('\\s*\\.\\s*'), value=np.nan, inplace=True)
    tm.assert_frame_equal(dfmix, res.fillna('.'))
    res = dfobj.copy()
    res.replace(regex=re.compile('\\s*(\\.)\\s*'), value='\\1\\1\\1', inplace=True)
    objc = obj.copy()
    objc['a'] = ['a', 'b', '...', '...']
    expec = DataFrame(objc)
    tm.assert_frame_equal(res, expec)
    res = dfmix.copy()
    res.replace(regex=re.compile('\\s*(\\.)\\s*'), value='\\1\\1\\1', inplace=True)
    mixc = mix_ab.copy()
    mixc['b'] = ['a', 'b', '...', '...']
    expec = DataFrame(mixc)
    tm.assert_frame_equal(res, expec)