def test_concat_categorical_empty(self):
    s1 = pd.Series([], dtype='category')
    s2 = pd.Series([1, 2], dtype='category')
    tm.assert_series_equal(pd.concat([s1, s2], ignore_index=True), s2)
    tm.assert_series_equal(s1.append(s2, ignore_index=True), s2)
    tm.assert_series_equal(pd.concat([s2, s1], ignore_index=True), s2)
    tm.assert_series_equal(s2.append(s1, ignore_index=True), s2)
    s1 = pd.Series([], dtype='category')
    s2 = pd.Series([], dtype='category')
    tm.assert_series_equal(pd.concat([s1, s2], ignore_index=True), s2)
    tm.assert_series_equal(s1.append(s2, ignore_index=True), s2)
    s1 = pd.Series([], dtype='category')
    s2 = pd.Series([], dtype='object')
    tm.assert_series_equal(pd.concat([s1, s2], ignore_index=True), s2)
    tm.assert_series_equal(s1.append(s2, ignore_index=True), s2)
    tm.assert_series_equal(pd.concat([s2, s1], ignore_index=True), s2)
    tm.assert_series_equal(s2.append(s1, ignore_index=True), s2)
    s1 = pd.Series([], dtype='category')
    s2 = pd.Series([np.nan, np.nan])
    exp = pd.Series([np.nan, np.nan])
    tm.assert_series_equal(pd.concat([s1, s2], ignore_index=True), exp)
    tm.assert_series_equal(s1.append(s2, ignore_index=True), exp)
    tm.assert_series_equal(pd.concat([s2, s1], ignore_index=True), exp)
    tm.assert_series_equal(s2.append(s1, ignore_index=True), exp)