def test_rsplit_to_dataframe_expand(self):
    s = Series(['nosplit', 'alsonosplit'])
    result = s.str.rsplit('_', expand=True)
    exp = DataFrame({0: Series(['nosplit', 'alsonosplit'])})
    tm.assert_frame_equal(result, exp)
    s = Series(['some_equal_splits', 'with_no_nans'])
    result = s.str.rsplit('_', expand=True)
    exp = DataFrame({0: ['some', 'with'], 1: ['equal', 'no'], 2: ['splits', 'nans']})
    tm.assert_frame_equal(result, exp)
    result = s.str.rsplit('_', expand=True, n=2)
    exp = DataFrame({0: ['some', 'with'], 1: ['equal', 'no'], 2: ['splits', 'nans']})
    tm.assert_frame_equal(result, exp)
    result = s.str.rsplit('_', expand=True, n=1)
    exp = DataFrame({0: ['some_equal', 'with_no'], 1: ['splits', 'nans']})
    tm.assert_frame_equal(result, exp)
    s = Series(['some_splits', 'with_index'], index=['preserve', 'me'])
    result = s.str.rsplit('_', expand=True)
    exp = DataFrame({0: ['some', 'with'], 1: ['splits', 'index']}, index=['preserve', 'me'])
    tm.assert_frame_equal(result, exp)