def test_partition_to_dataframe(self):
    values = Series(['a_b_c', 'c_d_e', np.nan, 'f_g_h', None])
    result = values.str.partition('_')
    exp = DataFrame({0: ['a', 'c', np.nan, 'f', None], 1: ['_', '_', np.nan, '_', None], 2: ['b_c', 'd_e', np.nan, 'g_h', None]})
    tm.assert_frame_equal(result, exp)
    result = values.str.rpartition('_')
    exp = DataFrame({0: ['a_b', 'c_d', np.nan, 'f_g', None], 1: ['_', '_', np.nan, '_', None], 2: ['c', 'e', np.nan, 'h', None]})
    tm.assert_frame_equal(result, exp)
    values = Series(['a_b_c', 'c_d_e', np.nan, 'f_g_h', None])
    result = values.str.partition('_', expand=True)
    exp = DataFrame({0: ['a', 'c', np.nan, 'f', None], 1: ['_', '_', np.nan, '_', None], 2: ['b_c', 'd_e', np.nan, 'g_h', None]})
    tm.assert_frame_equal(result, exp)
    result = values.str.rpartition('_', expand=True)
    exp = DataFrame({0: ['a_b', 'c_d', np.nan, 'f_g', None], 1: ['_', '_', np.nan, '_', None], 2: ['c', 'e', np.nan, 'h', None]})
    tm.assert_frame_equal(result, exp)