@pytest.mark.parametrize('fname, sname, expected_name', [('A', 'A', 'A'), ('A', 'B', None), ('A', None, None), (None, 'B', None), (None, None, None)])
def test_corner_union(self, indices, fname, sname, expected_name):
    if isinstance(indices, MultiIndex) or not indices.is_unique:
        pytest.skip('Not for MultiIndex or repeated indices')
    first = indices.copy().set_names(fname)
    second = indices.copy().set_names(sname)
    union = first.union(second)
    expected = indices.copy().set_names(expected_name)
    tm.assert_index_equal(union, expected)
    first = indices.copy().set_names(fname)
    second = indices.drop(indices).set_names(sname)
    union = first.union(second)
    expected = indices.copy().set_names(expected_name)
    tm.assert_index_equal(union, expected)
    first = indices.drop(indices).set_names(fname)
    second = indices.copy().set_names(sname)
    union = first.union(second)
    expected = indices.copy().set_names(expected_name)
    tm.assert_index_equal(union, expected)
    first = indices.drop(indices).set_names(fname)
    second = indices.drop(indices).set_names(sname)
    union = first.union(second)
    expected = indices.drop(indices).set_names(expected_name)
    tm.assert_index_equal(union, expected)