def test_int_array(self, kind, mix, all_arithmetic_functions):
    op = all_arithmetic_functions
    dtype = np.int64
    values = self._base([0, 1, 2, 0, 0, 0, 1, 2, 1, 0], dtype=dtype)
    rvalues = self._base([2, 0, 2, 3, 0, 0, 1, 5, 2, 0], dtype=dtype)
    a = self._klass(values, dtype=dtype, kind=kind)
    assert a.dtype == SparseDtype(dtype)
    b = self._klass(rvalues, dtype=dtype, kind=kind)
    assert b.dtype == SparseDtype(dtype)
    self._check_numeric_ops(a, b, values, rvalues, mix, op)
    self._check_numeric_ops(a, b * 0, values, rvalues * 0, mix, op)
    a = self._klass(values, fill_value=0, dtype=dtype, kind=kind)
    assert a.dtype == SparseDtype(dtype)
    b = self._klass(rvalues, dtype=dtype, kind=kind)
    assert b.dtype == SparseDtype(dtype)
    self._check_numeric_ops(a, b, values, rvalues, mix, op)
    a = self._klass(values, fill_value=0, dtype=dtype, kind=kind)
    assert a.dtype == SparseDtype(dtype)
    b = self._klass(rvalues, fill_value=0, dtype=dtype, kind=kind)
    assert b.dtype == SparseDtype(dtype)
    self._check_numeric_ops(a, b, values, rvalues, mix, op)
    a = self._klass(values, fill_value=1, dtype=dtype, kind=kind)
    assert a.dtype == SparseDtype(dtype, fill_value=1)
    b = self._klass(rvalues, fill_value=2, dtype=dtype, kind=kind)
    assert b.dtype == SparseDtype(dtype, fill_value=2)
    self._check_numeric_ops(a, b, values, rvalues, mix, op)