def test_slice_replace(self):
    values = Series(['short', 'a bit longer', 'evenlongerthanthat', '', np.nan])
    exp = Series(['shrt', 'a it longer', 'evnlongerthanthat', '', np.nan])
    result = values.str.slice_replace(2, 3)
    tm.assert_series_equal(result, exp)
    exp = Series(['shzrt', 'a zit longer', 'evznlongerthanthat', 'z', np.nan])
    result = values.str.slice_replace(2, 3, 'z')
    tm.assert_series_equal(result, exp)
    exp = Series(['shzort', 'a zbit longer', 'evzenlongerthanthat', 'z', np.nan])
    result = values.str.slice_replace(2, 2, 'z')
    tm.assert_series_equal(result, exp)
    exp = Series(['shzort', 'a zbit longer', 'evzenlongerthanthat', 'z', np.nan])
    result = values.str.slice_replace(2, 1, 'z')
    tm.assert_series_equal(result, exp)
    exp = Series(['shorz', 'a bit longez', 'evenlongerthanthaz', 'z', np.nan])
    result = values.str.slice_replace(-1, None, 'z')
    tm.assert_series_equal(result, exp)
    exp = Series(['zrt', 'zer', 'zat', 'z', np.nan])
    result = values.str.slice_replace(None, -2, 'z')
    tm.assert_series_equal(result, exp)
    exp = Series(['shortz', 'a bit znger', 'evenlozerthanthat', 'z', np.nan])
    result = values.str.slice_replace(6, 8, 'z')
    tm.assert_series_equal(result, exp)
    exp = Series(['zrt', 'a zit longer', 'evenlongzerthanthat', 'z', np.nan])
    result = values.str.slice_replace(-10, 3, 'z')
    tm.assert_series_equal(result, exp)