def test_get_indexer(self):
    index = self.create_index()
    target = Int64Index(np.arange(10))
    indexer = index.get_indexer(target)
    expected = np.array([0, -1, 1, -1, 2, -1, 3, -1, 4, -1], dtype=np.intp)
    tm.assert_numpy_array_equal(indexer, expected)
    target = Int64Index(np.arange(10))
    indexer = index.get_indexer(target, method='pad')
    expected = np.array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4], dtype=np.intp)
    tm.assert_numpy_array_equal(indexer, expected)
    target = Int64Index(np.arange(10))
    indexer = index.get_indexer(target, method='backfill')
    expected = np.array([0, 1, 1, 2, 2, 3, 3, 4, 4, 5], dtype=np.intp)
    tm.assert_numpy_array_equal(indexer, expected)