def test_drop_duplicates(self):
    base = pd.timedelta_range('1 day', '31 day', freq='D', name='idx')
    idx = base.append(base[:5])
    res = idx.drop_duplicates()
    tm.assert_index_equal(res, base)
    res = Series(idx).drop_duplicates()
    tm.assert_series_equal(res, Series(base))
    res = idx.drop_duplicates(keep='last')
    exp = base[5:].append(base[:5])
    tm.assert_index_equal(res, exp)
    res = Series(idx).drop_duplicates(keep='last')
    tm.assert_series_equal(res, Series(exp, index=np.arange(5, 36)))
    res = idx.drop_duplicates(keep=False)
    tm.assert_index_equal(res, base[5:])
    res = Series(idx).drop_duplicates(keep=False)
    tm.assert_series_equal(res, Series(base[5:], index=np.arange(5, 31)))