def test_astype(self):
    ci = self.create_index()
    result = ci.astype(object)
    tm.assert_index_equal(result, Index(np.array(ci)))
    assert result.equals(ci)
    assert isinstance(result, Index)
    assert not isinstance(result, CategoricalIndex)
    ii = IntervalIndex.from_arrays(left=[-0.001, 2.0], right=[2, 4], closed='right')
    ci = CategoricalIndex(Categorical.from_codes([0, 1, -1], categories=ii, ordered=True))
    result = ci.astype('interval')
    expected = ii.take([0, 1, -1])
    tm.assert_index_equal(result, expected)
    result = IntervalIndex(result.values)
    tm.assert_index_equal(result, expected)