def test_concat_axis_parameter(self):
    df1 = pd.DataFrame({'A': [0.1, 0.2]}, index=range(2))
    df2 = pd.DataFrame({'A': [0.3, 0.4]}, index=range(2))
    expected_index = pd.DataFrame({'A': [0.1, 0.2, 0.3, 0.4]}, index=[0, 1, 0, 1])
    concatted_index = pd.concat([df1, df2], axis='index')
    tm.assert_frame_equal(concatted_index, expected_index)
    concatted_row = pd.concat([df1, df2], axis='rows')
    tm.assert_frame_equal(concatted_row, expected_index)
    concatted_0 = pd.concat([df1, df2], axis=0)
    tm.assert_frame_equal(concatted_0, expected_index)
    expected_columns = pd.DataFrame([[0.1, 0.3], [0.2, 0.4]], index=[0, 1], columns=['A', 'A'])
    concatted_columns = pd.concat([df1, df2], axis='columns')
    tm.assert_frame_equal(concatted_columns, expected_columns)
    concatted_1 = pd.concat([df1, df2], axis=1)
    tm.assert_frame_equal(concatted_1, expected_columns)
    series1 = pd.Series([0.1, 0.2])
    series2 = pd.Series([0.3, 0.4])
    expected_index_series = pd.Series([0.1, 0.2, 0.3, 0.4], index=[0, 1, 0, 1])
    concatted_index_series = pd.concat([series1, series2], axis='index')
    tm.assert_series_equal(concatted_index_series, expected_index_series)
    concatted_row_series = pd.concat([series1, series2], axis='rows')
    tm.assert_series_equal(concatted_row_series, expected_index_series)
    concatted_0_series = pd.concat([series1, series2], axis=0)
    tm.assert_series_equal(concatted_0_series, expected_index_series)
    expected_columns_series = pd.DataFrame([[0.1, 0.3], [0.2, 0.4]], index=[0, 1], columns=[0, 1])
    concatted_columns_series = pd.concat([series1, series2], axis='columns')
    tm.assert_frame_equal(concatted_columns_series, expected_columns_series)
    concatted_1_series = pd.concat([series1, series2], axis=1)
    tm.assert_frame_equal(concatted_1_series, expected_columns_series)
    with pytest.raises(ValueError, match='No axis named'):
        pd.concat([series1, series2], axis='something')