def test_merge_incompat_infer_boolean_object(self):
    df1 = DataFrame({'key': Series([True, False], dtype=object)})
    df2 = DataFrame({'key': [True, False]})
    expected = DataFrame({'key': [True, False]}, dtype=object)
    result = pd.merge(df1, df2, on='key')
    tm.assert_frame_equal(result, expected)
    result = pd.merge(df2, df1, on='key')
    tm.assert_frame_equal(result, expected)
    df1 = DataFrame({'key': Series([True, False, np.nan], dtype=object)})
    df2 = DataFrame({'key': [True, False]})
    expected = DataFrame({'key': [True, False]}, dtype=object)
    result = pd.merge(df1, df2, on='key')
    tm.assert_frame_equal(result, expected)
    result = pd.merge(df2, df1, on='key')
    tm.assert_frame_equal(result, expected)