def test_merge(self):
    avals = tm.randn(2, 10)
    bvals = tm.randn(2, 10)
    ref_cols = Index(['e', 'a', 'b', 'd', 'f'])
    ablock = make_block(avals, ref_cols.get_indexer(['e', 'b']))
    bblock = make_block(bvals, ref_cols.get_indexer(['a', 'd']))
    merged = ablock.merge(bblock)
    tm.assert_numpy_array_equal(merged.mgr_locs.as_array, np.array([0, 1, 2, 3], dtype=np.int64))
    tm.assert_numpy_array_equal(merged.values[[0, 2]], np.array(avals))
    tm.assert_numpy_array_equal(merged.values[[1, 3]], np.array(bvals))