def test_strip_lstrip_rstrip_mixed(self):
    mixed = Series(['  aa  ', np.nan, ' bb \t\n', True, datetime.today(), None, 1, 2.0])
    rs = Series(mixed).str.strip()
    xp = Series(['aa', np.nan, 'bb', np.nan, np.nan, np.nan, np.nan, np.nan])
    assert isinstance(rs, Series)
    tm.assert_almost_equal(rs, xp)
    rs = Series(mixed).str.lstrip()
    xp = Series(['aa  ', np.nan, 'bb \t\n', np.nan, np.nan, np.nan, np.nan, np.nan])
    assert isinstance(rs, Series)
    tm.assert_almost_equal(rs, xp)
    rs = Series(mixed).str.rstrip()
    xp = Series(['  aa', np.nan, ' bb', np.nan, np.nan, np.nan, np.nan, np.nan])
    assert isinstance(rs, Series)
    tm.assert_almost_equal(rs, xp)