def test_partition_series(self):
    values = Series(['a_b_c', 'c_d_e', np.nan, 'f_g_h', None])
    result = values.str.partition('_', expand=False)
    exp = Series([('a', '_', 'b_c'), ('c', '_', 'd_e'), np.nan, ('f', '_', 'g_h'), None])
    tm.assert_series_equal(result, exp)
    result = values.str.rpartition('_', expand=False)
    exp = Series([('a_b', '_', 'c'), ('c_d', '_', 'e'), np.nan, ('f_g', '_', 'h'), None])
    tm.assert_series_equal(result, exp)
    values = Series(['a__b__c', 'c__d__e', np.nan, 'f__g__h', None])
    result = values.str.partition('__', expand=False)
    exp = Series([('a', '__', 'b__c'), ('c', '__', 'd__e'), np.nan, ('f', '__', 'g__h'), None])
    tm.assert_series_equal(result, exp)
    result = values.str.rpartition('__', expand=False)
    exp = Series([('a__b', '__', 'c'), ('c__d', '__', 'e'), np.nan, ('f__g', '__', 'h'), None])
    tm.assert_series_equal(result, exp)
    values = Series(['a b c', 'c d e', np.nan, 'f g h', None])
    result = values.str.partition(expand=False)
    exp = Series([('a', ' ', 'b c'), ('c', ' ', 'd e'), np.nan, ('f', ' ', 'g h'), None])
    tm.assert_series_equal(result, exp)
    result = values.str.rpartition(expand=False)
    exp = Series([('a b', ' ', 'c'), ('c d', ' ', 'e'), np.nan, ('f g', ' ', 'h'), None])
    tm.assert_series_equal(result, exp)
    values = Series(['abc', 'cde', np.nan, 'fgh', None])
    result = values.str.partition('_', expand=False)
    exp = Series([('abc', '', ''), ('cde', '', ''), np.nan, ('fgh', '', ''), None])
    tm.assert_series_equal(result, exp)
    result = values.str.rpartition('_', expand=False)
    exp = Series([('', '', 'abc'), ('', '', 'cde'), np.nan, ('', '', 'fgh'), None])
    tm.assert_series_equal(result, exp)
    values = Series(['a_b_c', 'c_d_e', np.nan, 'f_g_h'])
    result = values.str.partition('_', expand=False)
    exp = Series([('a', '_', 'b_c'), ('c', '_', 'd_e'), np.nan, ('f', '_', 'g_h')])
    tm.assert_series_equal(result, exp)
    result = values.str.rpartition('_', expand=False)
    exp = Series([('a_b', '_', 'c'), ('c_d', '_', 'e'), np.nan, ('f_g', '_', 'h')])
    tm.assert_series_equal(result, exp)
    values = Series(['A_B_C', 'B_C_D', 'E_F_G', 'EFGHEF'])
    result = values.str.partition('_', expand=False).tolist()
    assert result == [v.partition('_') for v in values]
    result = values.str.rpartition('_', expand=False).tolist()
    assert result == [v.rpartition('_') for v in values]