def test_operation_on_NaT(self):
    df = pd.DataFrame({'foo': [pd.NaT, pd.NaT, pd.Timestamp('2012-05-01')]})
    res = df.min()
    exp = pd.Series([pd.Timestamp('2012-05-01')], index=['foo'])
    tm.assert_series_equal(res, exp)
    res = df.max()
    exp = pd.Series([pd.Timestamp('2012-05-01')], index=['foo'])
    tm.assert_series_equal(res, exp)
    df = pd.DataFrame({'foo': [pd.NaT, pd.NaT]})
    res = df.min()
    exp = pd.Series([pd.NaT], index=['foo'])
    tm.assert_series_equal(res, exp)
    res = df.max()
    exp = pd.Series([pd.NaT], index=['foo'])
    tm.assert_series_equal(res, exp)