def test_find(self):
    values = Series(['ABCDEFG', 'BCDEFEF', 'DEFGHIJEF', 'EFGHEF', 'XXXX'])
    result = values.str.find('EF')
    tm.assert_series_equal(result, Series([4, 3, 1, 0, -1]))
    expected = np.array([v.find('EF') for v in values.values], dtype=np.int64)
    tm.assert_numpy_array_equal(result.values, expected)
    result = values.str.rfind('EF')
    tm.assert_series_equal(result, Series([4, 5, 7, 4, -1]))
    expected = np.array([v.rfind('EF') for v in values.values], dtype=np.int64)
    tm.assert_numpy_array_equal(result.values, expected)
    result = values.str.find('EF', 3)
    tm.assert_series_equal(result, Series([4, 3, 7, 4, -1]))
    expected = np.array([v.find('EF', 3) for v in values.values], dtype=np.int64)
    tm.assert_numpy_array_equal(result.values, expected)
    result = values.str.rfind('EF', 3)
    tm.assert_series_equal(result, Series([4, 5, 7, 4, -1]))
    expected = np.array([v.rfind('EF', 3) for v in values.values], dtype=np.int64)
    tm.assert_numpy_array_equal(result.values, expected)
    result = values.str.find('EF', 3, 6)
    tm.assert_series_equal(result, Series([4, 3, -1, 4, -1]))
    expected = np.array([v.find('EF', 3, 6) for v in values.values], dtype=np.int64)
    tm.assert_numpy_array_equal(result.values, expected)
    result = values.str.rfind('EF', 3, 6)
    tm.assert_series_equal(result, Series([4, 3, -1, 4, -1]))
    expected = np.array([v.rfind('EF', 3, 6) for v in values.values], dtype=np.int64)
    tm.assert_numpy_array_equal(result.values, expected)
    with pytest.raises(TypeError, match='expected a string object, not int'):
        result = values.str.find(0)
    with pytest.raises(TypeError, match='expected a string object, not int'):
        result = values.str.rfind(0)