def test_default_index(self):
    s1 = pd.Series([1, 2, 3], name='x')
    s2 = pd.Series([4, 5, 6], name='y')
    res = pd.concat([s1, s2], axis=1, ignore_index=True)
    assert isinstance(res.columns, pd.RangeIndex)
    exp = pd.DataFrame([[1, 4], [2, 5], [3, 6]])
    tm.assert_frame_equal(res, exp, check_index_type=True, check_column_type=True)
    s1 = pd.Series([1, 2, 3])
    s2 = pd.Series([4, 5, 6])
    res = pd.concat([s1, s2], axis=1, ignore_index=False)
    assert isinstance(res.columns, pd.RangeIndex)
    exp = pd.DataFrame([[1, 4], [2, 5], [3, 6]])
    exp.columns = pd.RangeIndex(2)
    tm.assert_frame_equal(res, exp, check_index_type=True, check_column_type=True)
    df1 = pd.DataFrame({'A': [1, 2], 'B': [5, 6]})
    df2 = pd.DataFrame({'A': [3, 4], 'B': [7, 8]})
    res = pd.concat([df1, df2], axis=0, ignore_index=True)
    exp = pd.DataFrame([[1, 5], [2, 6], [3, 7], [4, 8]], columns=['A', 'B'])
    tm.assert_frame_equal(res, exp, check_index_type=True, check_column_type=True)
    res = pd.concat([df1, df2], axis=1, ignore_index=True)
    exp = pd.DataFrame([[1, 5, 3, 7], [2, 6, 4, 8]])
    tm.assert_frame_equal(res, exp, check_index_type=True, check_column_type=True)