def test_findall(self):
    values = Series(['fooBAD__barBAD', np.nan, 'foo', 'BAD'])
    result = values.str.findall('BAD[_]*')
    exp = Series([['BAD__', 'BAD'], np.nan, [], ['BAD']])
    tm.assert_almost_equal(result, exp)
    mixed = Series(['fooBAD__barBAD', np.nan, 'foo', True, datetime.today(), 'BAD', None, 1, 2.0])
    rs = Series(mixed).str.findall('BAD[_]*')
    xp = Series([['BAD__', 'BAD'], np.nan, [], np.nan, np.nan, ['BAD'], np.nan, np.nan, np.nan])
    assert isinstance(rs, Series)
    tm.assert_almost_equal(rs, xp)