def test_basic(self):
    assert is_categorical_dtype(self.dtype)
    factor = Categorical(['a', 'b', 'b', 'a', 'a', 'c', 'c', 'c'])
    s = Series(factor, name='A')
    assert is_categorical_dtype(s.dtype)
    assert is_categorical_dtype(s)
    assert not is_categorical_dtype(np.dtype('float64'))
    assert is_categorical(s.dtype)
    assert is_categorical(s)
    assert not is_categorical(np.dtype('float64'))
    assert not is_categorical(1.0)