def test_dtype_on_categorical_dates(self):
    df = pd.DataFrame([[date(2001, 1, 1), 1.1], [date(2001, 1, 2), 1.3]], columns=['date', 'num2'])
    df['date'] = df['date'].astype('category')
    df2 = pd.DataFrame([[date(2001, 1, 1), 1.3], [date(2001, 1, 3), 1.4]], columns=['date', 'num4'])
    df2['date'] = df2['date'].astype('category')
    expected_outer = pd.DataFrame([[pd.Timestamp('2001-01-01'), 1.1, 1.3], [pd.Timestamp('2001-01-02'), 1.3, np.nan], [pd.Timestamp('2001-01-03'), np.nan, 1.4]], columns=['date', 'num2', 'num4'])
    result_outer = pd.merge(df, df2, how='outer', on=['date'])
    tm.assert_frame_equal(result_outer, expected_outer)
    expected_inner = pd.DataFrame([[pd.Timestamp('2001-01-01'), 1.1, 1.3]], columns=['date', 'num2', 'num4'])
    result_inner = pd.merge(df, df2, how='inner', on=['date'])
    tm.assert_frame_equal(result_inner, expected_inner)