def test_shift(self, datetime_series):
    shifted = datetime_series.shift(1)
    unshifted = shifted.shift(-1)
    tm.assert_index_equal(shifted.index, datetime_series.index)
    tm.assert_index_equal(unshifted.index, datetime_series.index)
    tm.assert_numpy_array_equal(unshifted.dropna().values, datetime_series.values[:-1])
    offset = BDay()
    shifted = datetime_series.shift(1, freq=offset)
    unshifted = shifted.shift(-1, freq=offset)
    tm.assert_series_equal(unshifted, datetime_series)
    unshifted = datetime_series.shift(0, freq=offset)
    tm.assert_series_equal(unshifted, datetime_series)
    shifted = datetime_series.shift(1, freq='B')
    unshifted = shifted.shift(-1, freq='B')
    tm.assert_series_equal(unshifted, datetime_series)
    unshifted = datetime_series.shift(0)
    tm.assert_series_equal(unshifted, datetime_series)
    ps = tm.makePeriodSeries()
    shifted = ps.shift(1)
    unshifted = shifted.shift(-1)
    tm.assert_index_equal(shifted.index, ps.index)
    tm.assert_index_equal(unshifted.index, ps.index)
    tm.assert_numpy_array_equal(unshifted.dropna().values, ps.values[:-1])
    shifted2 = ps.shift(1, 'B')
    shifted3 = ps.shift(1, BDay())
    tm.assert_series_equal(shifted2, shifted3)
    tm.assert_series_equal(ps, shifted2.shift(-1, 'B'))
    msg = 'Given freq D does not match PeriodIndex freq B'
    with pytest.raises(ValueError, match=msg):
        ps.shift(freq='D')
    shifted4 = ps.shift(1, freq='B')
    tm.assert_series_equal(shifted2, shifted4)
    shifted5 = ps.shift(1, freq=BDay())
    tm.assert_series_equal(shifted5, shifted4)
    index = date_range('2000-01-01', periods=5)
    for dtype in ['int32', 'int64']:
        s1 = Series(np.arange(5, dtype=dtype), index=index)
        p = s1.iloc[1]
        result = s1.shift(periods=p)
        expected = Series([np.nan, 0, 1, 2, 3], index=index)
        tm.assert_series_equal(result, expected)
    s = Series(date_range('2000-01-01 09:00:00', periods=5, tz='US/Eastern'), name='foo')
    result = s - s.shift()
    exp = Series(TimedeltaIndex(['NaT'] + ['1 days'] * 4), name='foo')
    tm.assert_series_equal(result, exp)
    s2 = Series(date_range('2000-01-01 09:00:00', periods=5, tz='CET'), name='foo')
    msg = 'DatetimeArray subtraction must have the same timezones or no timezones'
    with pytest.raises(TypeError, match=msg):
        s - s2