def test_unique(self):
    cat = Categorical(['a', 'b'])
    exp = Index(['a', 'b'])
    res = cat.unique()
    tm.assert_index_equal(res.categories, exp)
    tm.assert_categorical_equal(res, cat)
    cat = Categorical(['a', 'b', 'a', 'a'], categories=['a', 'b', 'c'])
    res = cat.unique()
    tm.assert_index_equal(res.categories, exp)
    tm.assert_categorical_equal(res, Categorical(exp))
    cat = Categorical(['c', 'a', 'b', 'a', 'a'], categories=['a', 'b', 'c'])
    exp = Index(['c', 'a', 'b'])
    res = cat.unique()
    tm.assert_index_equal(res.categories, exp)
    exp_cat = Categorical(exp, categories=['c', 'a', 'b'])
    tm.assert_categorical_equal(res, exp_cat)
    cat = Categorical(['b', np.nan, 'b', np.nan, 'a'], categories=['a', 'b', 'c'])
    res = cat.unique()
    exp = Index(['b', 'a'])
    tm.assert_index_equal(res.categories, exp)
    exp_cat = Categorical(['b', np.nan, 'a'], categories=['b', 'a'])
    tm.assert_categorical_equal(res, exp_cat)