def test_to_timedelta_on_missing_values(self):
    timedelta_NaT = np.timedelta64('NaT')
    actual = pd.to_timedelta(Series(['00:00:01', np.nan]))
    expected = Series([np.timedelta64(1000000000, 'ns'), timedelta_NaT], dtype='<m8[ns]')
    tm.assert_series_equal(actual, expected)
    actual = pd.to_timedelta(Series(['00:00:01', pd.NaT]))
    tm.assert_series_equal(actual, expected)
    actual = pd.to_timedelta(np.nan)
    assert actual.value == timedelta_NaT.astype('int64')
    actual = pd.to_timedelta(pd.NaT)
    assert actual.value == timedelta_NaT.astype('int64')