def test_extract_series(self):
    for series_name in (None, 'series_name'):
        s = Series(['A1', 'B2', 'C3'], name=series_name)
        result = s.str.extract('(_)', expand=True)
        exp = DataFrame([np.nan, np.nan, np.nan], dtype=object)
        tm.assert_frame_equal(result, exp)
        result = s.str.extract('(_)(_)', expand=True)
        exp = DataFrame([[np.nan, np.nan], [np.nan, np.nan], [np.nan, np.nan]], dtype=object)
        tm.assert_frame_equal(result, exp)
        result = s.str.extract('([AB])[123]', expand=True)
        exp = DataFrame(['A', 'B', np.nan])
        tm.assert_frame_equal(result, exp)
        result = s.str.extract('([AB])([123])', expand=True)
        exp = DataFrame([['A', '1'], ['B', '2'], [np.nan, np.nan]])
        tm.assert_frame_equal(result, exp)
        result = s.str.extract('(?P<letter>[AB])', expand=True)
        exp = DataFrame({'letter': ['A', 'B', np.nan]})
        tm.assert_frame_equal(result, exp)
        result = s.str.extract('(?P<letter>[AB])(?P<number>[123])', expand=True)
        e_list = [['A', '1'], ['B', '2'], [np.nan, np.nan]]
        exp = DataFrame(e_list, columns=['letter', 'number'])
        tm.assert_frame_equal(result, exp)
        result = s.str.extract('([AB])(?P<number>[123])', expand=True)
        exp = DataFrame(e_list, columns=[0, 'number'])
        tm.assert_frame_equal(result, exp)
        result = s.str.extract('([AB])(?:[123])', expand=True)
        exp = DataFrame(['A', 'B', np.nan])
        tm.assert_frame_equal(result, exp)