def test_rsplit(self):
    values = Series(['a_b_c', 'c_d_e', np.nan, 'f_g_h'])
    result = values.str.rsplit('_')
    exp = Series([['a', 'b', 'c'], ['c', 'd', 'e'], np.nan, ['f', 'g', 'h']])
    tm.assert_series_equal(result, exp)
    values = Series(['a__b__c', 'c__d__e', np.nan, 'f__g__h'])
    result = values.str.rsplit('__')
    tm.assert_series_equal(result, exp)
    result = values.str.rsplit('__', expand=False)
    tm.assert_series_equal(result, exp)
    mixed = Series(['a_b_c', np.nan, 'd_e_f', True, datetime.today(), None, 1, 2.0])
    result = mixed.str.rsplit('_')
    exp = Series([['a', 'b', 'c'], np.nan, ['d', 'e', 'f'], np.nan, np.nan, np.nan, np.nan, np.nan])
    assert isinstance(result, Series)
    tm.assert_almost_equal(result, exp)
    result = mixed.str.rsplit('_', expand=False)
    assert isinstance(result, Series)
    tm.assert_almost_equal(result, exp)
    values = Series(['a,b_c', 'c_d,e', np.nan, 'f,g,h'])
    result = values.str.rsplit('[,_]')
    exp = Series([['a,b_c'], ['c_d,e'], np.nan, ['f,g,h']])
    tm.assert_series_equal(result, exp)
    values = Series(['a_b_c', 'c_d_e', np.nan, 'f_g_h'])
    result = values.str.rsplit('_', n=1)
    exp = Series([['a_b', 'c'], ['c_d', 'e'], np.nan, ['f_g', 'h']])
    tm.assert_series_equal(result, exp)