def test_concat_empty_series(self):
    s1 = pd.Series([1, 2, 3], name='x')
    s2 = pd.Series(name='y', dtype='float64')
    res = pd.concat([s1, s2], axis=1)
    exp = pd.DataFrame({'x': [1, 2, 3], 'y': [np.nan, np.nan, np.nan]}, index=pd.Index([0, 1, 2], dtype='O'))
    tm.assert_frame_equal(res, exp)
    s1 = pd.Series([1, 2, 3], name='x')
    s2 = pd.Series(name='y', dtype='float64')
    res = pd.concat([s1, s2], axis=0)
    exp = pd.Series([1, 2, 3])
    tm.assert_series_equal(res, exp)
    s1 = pd.Series([1, 2, 3], name='x')
    s2 = pd.Series(name=None, dtype='float64')
    res = pd.concat([s1, s2], axis=1)
    exp = pd.DataFrame({'x': [1, 2, 3], 0: [np.nan, np.nan, np.nan]}, columns=['x', 0], index=pd.Index([0, 1, 2], dtype='O'))
    tm.assert_frame_equal(res, exp)