def test_datetime_other_units(self):
    idx = pd.DatetimeIndex(['2011-01-01', 'NaT', '2011-01-02'])
    exp = np.array([False, True, False])
    tm.assert_numpy_array_equal(isna(idx), exp)
    tm.assert_numpy_array_equal(notna(idx), ~exp)
    tm.assert_numpy_array_equal(isna(idx.values), exp)
    tm.assert_numpy_array_equal(notna(idx.values), ~exp)
    for dtype in ['datetime64[D]', 'datetime64[h]', 'datetime64[m]', 'datetime64[s]', 'datetime64[ms]', 'datetime64[us]', 'datetime64[ns]']:
        values = idx.values.astype(dtype)
        exp = np.array([False, True, False])
        tm.assert_numpy_array_equal(isna(values), exp)
        tm.assert_numpy_array_equal(notna(values), ~exp)
        exp = pd.Series([False, True, False])
        s = pd.Series(values)
        tm.assert_series_equal(isna(s), exp)
        tm.assert_series_equal(notna(s), ~exp)
        s = pd.Series(values, dtype=object)
        tm.assert_series_equal(isna(s), exp)
        tm.assert_series_equal(notna(s), ~exp)