@pytest.mark.parametrize('freq', ['M', '2M', '3M'])
def test_parr_cmp_pi(self, freq, box_with_array):
    xbox = np.ndarray if box_with_array is pd.Index else box_with_array
    base = PeriodIndex(['2011-01', '2011-02', '2011-03', '2011-04'], freq=freq)
    base = tm.box_expected(base, box_with_array)
    idx = PeriodIndex(['2011-02', '2011-01', '2011-03', '2011-05'], freq=freq)
    exp = np.array([False, False, True, False])
    exp = tm.box_expected(exp, xbox)
    tm.assert_equal(base == idx, exp)
    exp = np.array([True, True, False, True])
    exp = tm.box_expected(exp, xbox)
    tm.assert_equal(base != idx, exp)
    exp = np.array([False, True, False, False])
    exp = tm.box_expected(exp, xbox)
    tm.assert_equal(base > idx, exp)
    exp = np.array([True, False, False, True])
    exp = tm.box_expected(exp, xbox)
    tm.assert_equal(base < idx, exp)
    exp = np.array([False, True, True, False])
    exp = tm.box_expected(exp, xbox)
    tm.assert_equal(base >= idx, exp)
    exp = np.array([True, False, True, True])
    exp = tm.box_expected(exp, xbox)
    tm.assert_equal(base <= idx, exp)