def test_maybe_convert_objects_uint64(self):
    arr = np.array([2 ** 63], dtype=object)
    exp = np.array([2 ** 63], dtype=np.uint64)
    tm.assert_numpy_array_equal(lib.maybe_convert_objects(arr), exp)
    arr = np.array([np.uint64(2 ** 63)], dtype=object)
    exp = np.array([2 ** 63], dtype=np.uint64)
    tm.assert_numpy_array_equal(lib.maybe_convert_objects(arr), exp)
    arr = np.array([2, -1], dtype=object)
    exp = np.array([2, -1], dtype=np.int64)
    tm.assert_numpy_array_equal(lib.maybe_convert_objects(arr), exp)
    arr = np.array([2 ** 63, -1], dtype=object)
    exp = np.array([2 ** 63, -1], dtype=object)
    tm.assert_numpy_array_equal(lib.maybe_convert_objects(arr), exp)