def test_combine_first_mixed_bug(self):
    idx = Index(['a', 'b', 'c', 'e'])
    ser1 = Series([5.0, -9.0, 4.0, 100.0], index=idx)
    ser2 = Series(['a', 'b', 'c', 'e'], index=idx)
    ser3 = Series([12, 4, 5, 97], index=idx)
    frame1 = DataFrame({'col0': ser1, 'col2': ser2, 'col3': ser3})
    idx = Index(['a', 'b', 'c', 'f'])
    ser1 = Series([5.0, -9.0, 4.0, 100.0], index=idx)
    ser2 = Series(['a', 'b', 'c', 'f'], index=idx)
    ser3 = Series([12, 4, 5, 97], index=idx)
    frame2 = DataFrame({'col1': ser1, 'col2': ser2, 'col5': ser3})
    combined = frame1.combine_first(frame2)
    assert len(combined.columns) == 5
    df = DataFrame([[1.0, 2.0, False, True], [4.0, 5.0, True, False]], columns=['A', 'B', 'bool1', 'bool2'])
    other = DataFrame([[45, 45]], index=[0], columns=['A', 'B'])
    result = df.combine_first(other)
    tm.assert_frame_equal(result, df)
    df.loc[0, 'A'] = np.nan
    result = df.combine_first(other)
    df.loc[0, 'A'] = 45
    tm.assert_frame_equal(result, df)
    df1 = DataFrame({'A': [1.0, np.nan, 3.0, 5.0, np.nan], 'B': [np.nan, 2.0, 3.0, np.nan, 6.0]})
    df2 = DataFrame({'A': [5.0, 2.0, 4.0, np.nan, 3.0, 7.0], 'B': [np.nan, np.nan, 3.0, 4.0, 6.0, 8.0]})
    result = df1.combine_first(df2)
    expected = DataFrame({'A': [1, 2, 3, 5, 3, 7.0], 'B': [np.nan, 2, 3, 4, 6, 8]})
    tm.assert_frame_equal(result, expected)
    df1 = DataFrame([[np.nan, 3.0, True], [-4.6, np.nan, True], [np.nan, 7.0, False]])
    df2 = DataFrame([[-42.6, np.nan, True], [-5.0, 1.6, False]], index=[1, 2])
    result = df1.combine_first(df2)[2]
    expected = Series([True, True, False], name=2)
    tm.assert_series_equal(result, expected)
    df0 = DataFrame({'a': [datetime(2000, 1, 1), datetime(2000, 1, 2), datetime(2000, 1, 3)]})
    df1 = DataFrame({'a': [None, None, None]})
    df2 = df1.combine_first(df0)
    tm.assert_frame_equal(df2, df0)
    df2 = df0.combine_first(df1)
    tm.assert_frame_equal(df2, df0)
    df0 = DataFrame({'a': [datetime(2000, 1, 1), datetime(2000, 1, 2), datetime(2000, 1, 3)]})
    df1 = DataFrame({'a': [datetime(2000, 1, 2), None, None]})
    df2 = df1.combine_first(df0)
    result = df0.copy()
    result.iloc[0, :] = df1.iloc[0, :]
    tm.assert_frame_equal(df2, result)
    df2 = df0.combine_first(df1)
    tm.assert_frame_equal(df2, df0)