def test_get_numeric_data(self):
    mgr = create_mgr('int: int; float: float; complex: complex;str: object; bool: bool; obj: object; dt: datetime', item_shape=(3,))
    mgr.set('obj', np.array([1, 2, 3], dtype=np.object_))
    numeric = mgr.get_numeric_data()
    tm.assert_index_equal(numeric.items, pd.Index(['int', 'float', 'complex', 'bool']))
    tm.assert_almost_equal(mgr.get('float').internal_values(), numeric.get('float').internal_values())
    numeric.set('float', np.array([100.0, 200.0, 300.0]))
    tm.assert_almost_equal(mgr.get('float').internal_values(), np.array([100.0, 200.0, 300.0]))
    numeric2 = mgr.get_numeric_data(copy=True)
    tm.assert_index_equal(numeric.items, pd.Index(['int', 'float', 'complex', 'bool']))
    numeric2.set('float', np.array([1000.0, 2000.0, 3000.0]))
    tm.assert_almost_equal(mgr.get('float').internal_values(), np.array([100.0, 200.0, 300.0]))