def test_join_inner(self):
    index = self.create_index()
    other = Int64Index([7, 12, 25, 1, 2, 5])
    other_mono = Int64Index([1, 2, 5, 7, 12, 25])
    res, lidx, ridx = index.join(other, how='inner', return_indexers=True)
    ind = res.argsort()
    res = res.take(ind)
    lidx = lidx.take(ind)
    ridx = ridx.take(ind)
    eres = Int64Index([2, 12])
    elidx = np.array([1, 6], dtype=np.intp)
    eridx = np.array([4, 1], dtype=np.intp)
    assert isinstance(res, Int64Index)
    tm.assert_index_equal(res, eres)
    tm.assert_numpy_array_equal(lidx, elidx)
    tm.assert_numpy_array_equal(ridx, eridx)
    res, lidx, ridx = index.join(other_mono, how='inner', return_indexers=True)
    res2 = index.intersection(other_mono)
    tm.assert_index_equal(res, res2)
    elidx = np.array([1, 6], dtype=np.intp)
    eridx = np.array([1, 4], dtype=np.intp)
    assert isinstance(res, Int64Index)
    tm.assert_index_equal(res, eres)
    tm.assert_numpy_array_equal(lidx, elidx)
    tm.assert_numpy_array_equal(ridx, eridx)