def test_endswith(self):
    values = Series(['om', np.nan, 'foo_nom', 'nom', 'bar_foo', np.nan, 'foo'])
    result = values.str.endswith('foo')
    exp = Series([False, np.nan, False, False, True, np.nan, True])
    tm.assert_series_equal(result, exp)
    result = values.str.endswith('foo', na=False)
    tm.assert_series_equal(result, exp.fillna(False).astype(bool))
    mixed = np.array(['a', np.nan, 'b', True, datetime.today(), 'foo', None, 1, 2.0], dtype=object)
    rs = strings.str_endswith(mixed, 'f')
    xp = np.array([False, np.nan, False, np.nan, np.nan, False, np.nan, np.nan, np.nan], dtype=np.object_)
    tm.assert_numpy_array_equal(rs, xp)
    rs = Series(mixed).str.endswith('f')
    xp = Series([False, np.nan, False, np.nan, np.nan, False, np.nan, np.nan, np.nan])
    assert isinstance(rs, Series)
    tm.assert_series_equal(rs, xp)