def test_count(self):
    frame = DataFrame()
    ct1 = frame.count(1)
    assert isinstance(ct1, Series)
    ct2 = frame.count(0)
    assert isinstance(ct2, Series)
    df = DataFrame(index=range(10))
    result = df.count(1)
    expected = Series(0, index=df.index)
    tm.assert_series_equal(result, expected)
    df = DataFrame(columns=range(10))
    result = df.count(0)
    expected = Series(0, index=df.columns)
    tm.assert_series_equal(result, expected)
    df = DataFrame()
    result = df.count()
    expected = Series(0, index=[])
    tm.assert_series_equal(result, expected)