def test_constructor(self):
    idx = UInt64Index([1, 2, 3])
    res = Index([1, 2, 3], dtype=np.uint64)
    tm.assert_index_equal(res, idx)
    idx = UInt64Index([1, 2 ** 63])
    res = Index([1, 2 ** 63], dtype=np.uint64)
    tm.assert_index_equal(res, idx)
    idx = UInt64Index([1, 2 ** 63])
    res = Index([1, 2 ** 63])
    tm.assert_index_equal(res, idx)
    idx = Index([-1, 2 ** 63], dtype=object)
    res = Index(np.array([-1, 2 ** 63], dtype=object))
    tm.assert_index_equal(res, idx)
    idx = UInt64Index([1, 2 ** 63 + 1], dtype=np.uint64)
    res = Index([1, 2 ** 63 + 1], dtype=np.uint64)
    tm.assert_index_equal(res, idx)