def test_is_scalar_builtin_scalars(self):
    assert is_scalar(None)
    assert is_scalar(True)
    assert is_scalar(False)
    assert is_scalar(Number())
    assert is_scalar(Fraction())
    assert is_scalar(0.0)
    assert is_scalar(np.nan)
    assert is_scalar('foobar')
    assert is_scalar(b'foobar')
    assert is_scalar(datetime(2014, 1, 1))
    assert is_scalar(date(2014, 1, 1))
    assert is_scalar(time(12, 0))
    assert is_scalar(timedelta(hours=1))
    assert is_scalar(pd.NaT)