def test_shift_categorical(self):
    s = pd.Series(['a', 'b', 'c', 'd'], dtype='category')
    tm.assert_series_equal(s.iloc[:-1], s.shift(1).shift(-1).dropna())
    sp1 = s.shift(1)
    tm.assert_index_equal(s.index, sp1.index)
    assert np.all(sp1.values.codes[:1] == -1)
    assert np.all(s.values.codes[:-1] == sp1.values.codes[1:])
    sn2 = s.shift(-2)
    tm.assert_index_equal(s.index, sn2.index)
    assert np.all(sn2.values.codes[-2:] == -1)
    assert np.all(s.values.codes[2:] == sn2.values.codes[:-2])
    tm.assert_index_equal(s.values.categories, sp1.values.categories)
    tm.assert_index_equal(s.values.categories, sn2.values.categories)