@pytest.mark.slow
def test_bar_edge(self):
    df = DataFrame({'A': [3] * 5, 'B': list(range(5))}, index=range(5))
    self._check_bar_alignment(df, kind='bar', stacked=True, align='edge')
    self._check_bar_alignment(df, kind='bar', stacked=True, width=0.9, align='edge')
    self._check_bar_alignment(df, kind='barh', stacked=True, align='edge')
    self._check_bar_alignment(df, kind='barh', stacked=True, width=0.9, align='edge')
    self._check_bar_alignment(df, kind='bar', stacked=False, align='edge')
    self._check_bar_alignment(df, kind='bar', stacked=False, width=0.9, align='edge')
    self._check_bar_alignment(df, kind='barh', stacked=False, align='edge')
    self._check_bar_alignment(df, kind='barh', stacked=False, width=0.9, align='edge')
    self._check_bar_alignment(df, kind='bar', subplots=True, align='edge')
    self._check_bar_alignment(df, kind='bar', subplots=True, width=0.9, align='edge')
    self._check_bar_alignment(df, kind='barh', subplots=True, align='edge')
    self._check_bar_alignment(df, kind='barh', subplots=True, width=0.9, align='edge')