@pytest.mark.slow
def test_hist_secondary_legend(self):
    df = DataFrame(np.random.randn(30, 4), columns=list('abcd'))
    _, ax = self.plt.subplots()
    ax = df['a'].plot.hist(legend=True, ax=ax)
    df['b'].plot.hist(ax=ax, legend=True, secondary_y=True)
    self._check_legend_labels(ax, labels=['a', 'b (right)'])
    assert ax.get_yaxis().get_visible()
    assert ax.right_ax.get_yaxis().get_visible()
    tm.close()
    _, ax = self.plt.subplots()
    ax = df['a'].plot.hist(legend=True, secondary_y=True, ax=ax)
    df['b'].plot.hist(ax=ax, legend=True, secondary_y=True)
    self._check_legend_labels(ax.left_ax, labels=['a (right)', 'b (right)'])
    assert not ax.left_ax.get_yaxis().get_visible()
    assert ax.get_yaxis().get_visible()
    tm.close()
    _, ax = self.plt.subplots()
    ax = df['a'].plot.hist(legend=True, secondary_y=True, ax=ax)
    df['b'].plot.hist(ax=ax, legend=True)
    self._check_legend_labels(ax.left_ax, labels=['a (right)', 'b'])
    assert ax.left_ax.get_yaxis().get_visible()
    assert ax.get_yaxis().get_visible()
    tm.close()