def test_asfreq_normalize(self):
    rng = date_range('1/1/2000 09:30', periods=20)
    norm = date_range('1/1/2000', periods=20)
    vals = np.random.randn(20)
    ts = Series(vals, index=rng)
    result = ts.asfreq('D', normalize=True)
    norm = date_range('1/1/2000', periods=20)
    expected = Series(vals, index=norm)
    tm.assert_series_equal(result, expected)
    vals = np.random.randn(20, 3)
    ts = DataFrame(vals, index=rng)
    result = ts.asfreq('D', normalize=True)
    expected = DataFrame(vals, index=norm)
    tm.assert_frame_equal(result, expected)