def test_downcast(self):
    o = self._construct(shape=4, value=9, dtype=np.int64)
    result = o.copy()
    result._data = o._data.downcast(dtypes='infer')
    self._compare(result, o)
    o = self._construct(shape=4, value=9.0)
    expected = o.astype(np.int64)
    result = o.copy()
    result._data = o._data.downcast(dtypes='infer')
    self._compare(result, expected)
    o = self._construct(shape=4, value=9.5)
    result = o.copy()
    result._data = o._data.downcast(dtypes='infer')
    self._compare(result, o)
    o = self._construct(shape=4, value=9.000000000005)
    result = o.copy()
    result._data = o._data.downcast(dtypes='infer')
    expected = o.astype(np.int64)
    self._compare(result, expected)