@pytest.mark.parametrize('index, columns', [([0, 0, 1, 1], pd.MultiIndex.from_product([[1, 2], ['a', 'b']])), ([0, 0, 2, 3], pd.MultiIndex.from_product([[1, 2], ['a', 'b']])), ([0, 1, 2, 3], pd.MultiIndex.from_product([[1, 2], ['a', 'b']]))])
def test_stack_multi_columns_non_unique_index(self, index, columns):
    df = pd.DataFrame(index=index, columns=columns).fillna(1)
    stacked = df.stack()
    new_index = pd.MultiIndex.from_tuples(stacked.index.to_numpy())
    expected = pd.DataFrame(stacked.to_numpy(), index=new_index, columns=stacked.columns)
    tm.assert_frame_equal(stacked, expected)
    stacked_codes = np.asarray(stacked.index.codes)
    expected_codes = np.asarray(new_index.codes)
    tm.assert_numpy_array_equal(stacked_codes, expected_codes)