def test_index(self):
    i = Index([23, 45, 18, 98, 43, 11], name='index')
    output = Index(ujson.decode(ujson.encode(i)), name='index')
    tm.assert_index_equal(i, output)
    output = Index(ujson.decode(ujson.encode(i), numpy=True), name='index')
    tm.assert_index_equal(i, output)
    dec = _clean_dict(ujson.decode(ujson.encode(i, orient='split')))
    output = Index(**dec)
    tm.assert_index_equal(i, output)
    assert i.name == output.name
    dec = _clean_dict(ujson.decode(ujson.encode(i, orient='split'), numpy=True))
    output = Index(**dec)
    tm.assert_index_equal(i, output)
    assert i.name == output.name
    output = Index(ujson.decode(ujson.encode(i, orient='values')), name='index')
    tm.assert_index_equal(i, output)
    output = Index(ujson.decode(ujson.encode(i, orient='values'), numpy=True), name='index')
    tm.assert_index_equal(i, output)
    output = Index(ujson.decode(ujson.encode(i, orient='records')), name='index')
    tm.assert_index_equal(i, output)
    output = Index(ujson.decode(ujson.encode(i, orient='records'), numpy=True), name='index')
    tm.assert_index_equal(i, output)
    output = Index(ujson.decode(ujson.encode(i, orient='index')), name='index')
    tm.assert_index_equal(i, output)
    output = Index(ujson.decode(ujson.encode(i, orient='index'), numpy=True), name='index')
    tm.assert_index_equal(i, output)