def test_append_empty_dataframe(self):
    df1 = DataFrame()
    df2 = DataFrame()
    result = df1.append(df2)
    expected = df1.copy()
    tm.assert_frame_equal(result, expected)
    df1 = DataFrame(np.random.randn(5, 2))
    df2 = DataFrame()
    result = df1.append(df2)
    expected = df1.copy()
    tm.assert_frame_equal(result, expected)
    df1 = DataFrame(columns=['bar', 'foo'])
    df2 = DataFrame()
    result = df1.append(df2)
    expected = df1.copy()
    tm.assert_frame_equal(result, expected)
    df1 = DataFrame(np.random.randn(5, 2), columns=['bar', 'foo'])
    df2 = DataFrame()
    result = df1.append(df2)
    expected = df1.copy()
    tm.assert_frame_equal(result, expected)