def test_reindexing(self):
    df = DataFrame({'A': np.arange(3, dtype='int64'), 'B': Series(list('abc')).astype(CDT(list('cabe')))}).set_index('B')
    result = df.reindex(['a', 'b', 'e'])
    expected = DataFrame({'A': [0, 1, np.nan], 'B': Series(list('abe'))}).set_index('B')
    tm.assert_frame_equal(result, expected, check_index_type=True)
    result = df.reindex(['a', 'b'])
    expected = DataFrame({'A': [0, 1], 'B': Series(list('ab'))}).set_index('B')
    tm.assert_frame_equal(result, expected, check_index_type=True)
    result = df.reindex(['e'])
    expected = DataFrame({'A': [np.nan], 'B': Series(['e'])}).set_index('B')
    tm.assert_frame_equal(result, expected, check_index_type=True)
    result = df.reindex(['d'])
    expected = DataFrame({'A': [np.nan], 'B': Series(['d'])}).set_index('B')
    tm.assert_frame_equal(result, expected, check_index_type=True)
    cats = list('cabe')
    result = df.reindex(Categorical(['a', 'e'], categories=cats))
    expected = DataFrame({'A': [0, np.nan], 'B': Series(list('ae')).astype(CDT(cats))}).set_index('B')
    tm.assert_frame_equal(result, expected, check_index_type=True)
    result = df.reindex(Categorical(['a'], categories=cats))
    expected = DataFrame({'A': [0], 'B': Series(list('a')).astype(CDT(cats))}).set_index('B')
    tm.assert_frame_equal(result, expected, check_index_type=True)
    result = df.reindex(['a', 'b', 'e'])
    expected = DataFrame({'A': [0, 1, np.nan], 'B': Series(list('abe'))}).set_index('B')
    tm.assert_frame_equal(result, expected, check_index_type=True)
    result = df.reindex(['a', 'b'])
    expected = DataFrame({'A': [0, 1], 'B': Series(list('ab'))}).set_index('B')
    tm.assert_frame_equal(result, expected, check_index_type=True)
    result = df.reindex(['e'])
    expected = DataFrame({'A': [np.nan], 'B': Series(['e'])}).set_index('B')
    tm.assert_frame_equal(result, expected, check_index_type=True)
    result = df.reindex(Categorical(['a', 'e'], categories=cats, ordered=True))
    expected = DataFrame({'A': [0, np.nan], 'B': Series(list('ae')).astype(CDT(cats, ordered=True))}).set_index('B')
    tm.assert_frame_equal(result, expected, check_index_type=True)
    result = df.reindex(Categorical(['a', 'd'], categories=['a', 'd']))
    expected = DataFrame({'A': [0, np.nan], 'B': Series(list('ad')).astype(CDT(['a', 'd']))}).set_index('B')
    tm.assert_frame_equal(result, expected, check_index_type=True)
    msg = 'cannot reindex from a duplicate axis'
    with pytest.raises(ValueError, match=msg):
        self.df2.reindex(['a', 'b'])
    msg = 'argument {} is not implemented for CategoricalIndex\\.reindex'
    with pytest.raises(NotImplementedError, match=msg.format('method')):
        df.reindex(['a'], method='ffill')
    with pytest.raises(NotImplementedError, match=msg.format('level')):
        df.reindex(['a'], level=1)
    with pytest.raises(NotImplementedError, match=msg.format('limit')):
        df.reindex(['a'], limit=2)