def test_categorical(self):
    expected = Categorical(list('bac'), categories=list('bac'))
    expected_o = Categorical(list('bac'), categories=list('abc'), ordered=True)
    c = Categorical(list('baabc'))
    result = c.unique()
    tm.assert_categorical_equal(result, expected)
    result = algos.unique(c)
    tm.assert_categorical_equal(result, expected)
    c = Categorical(list('baabc'), ordered=True)
    result = c.unique()
    tm.assert_categorical_equal(result, expected_o)
    result = algos.unique(c)
    tm.assert_categorical_equal(result, expected_o)
    s = Series(Categorical(list('baabc')), name='foo')
    result = s.unique()
    tm.assert_categorical_equal(result, expected)
    result = pd.unique(s)
    tm.assert_categorical_equal(result, expected)
    ci = CategoricalIndex(Categorical(list('baabc'), categories=list('bac')))
    expected = CategoricalIndex(expected)
    result = ci.unique()
    tm.assert_index_equal(result, expected)
    result = pd.unique(ci)
    tm.assert_index_equal(result, expected)