def test_sort_values_inplace(self):
    frame = DataFrame(np.random.randn(4, 4), index=[1, 2, 3, 4], columns=['A', 'B', 'C', 'D'])
    sorted_df = frame.copy()
    sorted_df.sort_values(by='A', inplace=True)
    expected = frame.sort_values(by='A')
    tm.assert_frame_equal(sorted_df, expected)
    sorted_df = frame.copy()
    sorted_df.sort_values(by=1, axis=1, inplace=True)
    expected = frame.sort_values(by=1, axis=1)
    tm.assert_frame_equal(sorted_df, expected)
    sorted_df = frame.copy()
    sorted_df.sort_values(by='A', ascending=False, inplace=True)
    expected = frame.sort_values(by='A', ascending=False)
    tm.assert_frame_equal(sorted_df, expected)
    sorted_df = frame.copy()
    sorted_df.sort_values(by=['A', 'B'], ascending=False, inplace=True)
    expected = frame.sort_values(by=['A', 'B'], ascending=False)
    tm.assert_frame_equal(sorted_df, expected)