def test_append_dtypes(self):
    df1 = DataFrame({'bar': Timestamp('20130101')}, index=range(5))
    df2 = DataFrame()
    result = df1.append(df2)
    expected = df1.copy()
    tm.assert_frame_equal(result, expected)
    df1 = DataFrame({'bar': Timestamp('20130101')}, index=range(1))
    df2 = DataFrame({'bar': 'foo'}, index=range(1, 2))
    result = df1.append(df2)
    expected = DataFrame({'bar': [Timestamp('20130101'), 'foo']})
    tm.assert_frame_equal(result, expected)
    df1 = DataFrame({'bar': Timestamp('20130101')}, index=range(1))
    df2 = DataFrame({'bar': np.nan}, index=range(1, 2))
    result = df1.append(df2)
    expected = DataFrame({'bar': Series([Timestamp('20130101'), np.nan], dtype='M8[ns]')})
    tm.assert_frame_equal(result, expected)
    df1 = DataFrame({'bar': Timestamp('20130101')}, index=range(1))
    df2 = DataFrame({'bar': np.nan}, index=range(1, 2), dtype=object)
    result = df1.append(df2)
    expected = DataFrame({'bar': Series([Timestamp('20130101'), np.nan], dtype='M8[ns]')})
    tm.assert_frame_equal(result, expected)
    df1 = DataFrame({'bar': np.nan}, index=range(1))
    df2 = DataFrame({'bar': Timestamp('20130101')}, index=range(1, 2))
    result = df1.append(df2)
    expected = DataFrame({'bar': Series([np.nan, Timestamp('20130101')], dtype='M8[ns]')})
    tm.assert_frame_equal(result, expected)
    df1 = DataFrame({'bar': Timestamp('20130101')}, index=range(1))
    df2 = DataFrame({'bar': 1}, index=range(1, 2), dtype=object)
    result = df1.append(df2)
    expected = DataFrame({'bar': Series([Timestamp('20130101'), 1])})
    tm.assert_frame_equal(result, expected)