def test_split_to_dataframe(self):
    s = Series(['nosplit', 'alsonosplit'])
    result = s.str.split('_', expand=True)
    exp = DataFrame({0: Series(['nosplit', 'alsonosplit'])})
    tm.assert_frame_equal(result, exp)
    s = Series(['some_equal_splits', 'with_no_nans'])
    result = s.str.split('_', expand=True)
    exp = DataFrame({0: ['some', 'with'], 1: ['equal', 'no'], 2: ['splits', 'nans']})
    tm.assert_frame_equal(result, exp)
    s = Series(['some_unequal_splits', 'one_of_these_things_is_not'])
    result = s.str.split('_', expand=True)
    exp = DataFrame({0: ['some', 'one'], 1: ['unequal', 'of'], 2: ['splits', 'these'], 3: [np.nan, 'things'], 4: [np.nan, 'is'], 5: [np.nan, 'not']})
    tm.assert_frame_equal(result, exp)
    s = Series(['some_splits', 'with_index'], index=['preserve', 'me'])
    result = s.str.split('_', expand=True)
    exp = DataFrame({0: ['some', 'with'], 1: ['splits', 'index']}, index=['preserve', 'me'])
    tm.assert_frame_equal(result, exp)
    with pytest.raises(ValueError, match='expand must be'):
        s.str.split('_', expand='not_a_boolean')