def test_frame_select_complex2(self, setup_path):
    with ensure_clean_path(['parms.hdf', 'hist.hdf']) as paths:
        pp, hh = paths
        parms = DataFrame({'A': [1, 1, 2, 2, 3]})
        parms.to_hdf(pp, 'df', mode='w', format='table', data_columns=['A'])
        selection = read_hdf(pp, 'df', where='A=[2,3]')
        hist = DataFrame(np.random.randn(25, 1), columns=['data'], index=MultiIndex.from_tuples([(i, j) for i in range(5) for j in range(5)], names=['l1', 'l2']))
        hist.to_hdf(hh, 'df', mode='w', format='table')
        expected = read_hdf(hh, 'df', where='l1=[2, 3, 4]')
        l = selection.index.tolist()
        store = HDFStore(hh)
        result = store.select('df', where='l1=l')
        tm.assert_frame_equal(result, expected)
        store.close()
        result = read_hdf(hh, 'df', where='l1=l')
        tm.assert_frame_equal(result, expected)
        index = selection.index
        result = read_hdf(hh, 'df', where='l1=index')
        tm.assert_frame_equal(result, expected)
        result = read_hdf(hh, 'df', where='l1=selection.index')
        tm.assert_frame_equal(result, expected)
        result = read_hdf(hh, 'df', where='l1=selection.index.tolist()')
        tm.assert_frame_equal(result, expected)
        result = read_hdf(hh, 'df', where='l1=list(selection.index)')
        tm.assert_frame_equal(result, expected)
        store = HDFStore(hh)
        result = store.select('df', where='l1=index')
        tm.assert_frame_equal(result, expected)
        result = store.select('df', where='l1=selection.index')
        tm.assert_frame_equal(result, expected)
        result = store.select('df', where='l1=selection.index.tolist()')
        tm.assert_frame_equal(result, expected)
        result = store.select('df', where='l1=list(selection.index)')
        tm.assert_frame_equal(result, expected)
        store.close()