def test_describe_option(self):
    self.cf.register_option('a', 1, 'doc')
    self.cf.register_option('b', 1, 'doc2')
    self.cf.deprecate_option('b')
    self.cf.register_option('c.d.e1', 1, 'doc3')
    self.cf.register_option('c.d.e2', 1, 'doc4')
    self.cf.register_option('f', 1)
    self.cf.register_option('g.h', 1)
    self.cf.register_option('k', 2)
    self.cf.deprecate_option('g.h', rkey='k')
    self.cf.register_option('l', 'foo')
    msg = 'No such keys\\(s\\)'
    with pytest.raises(OptionError, match=msg):
        self.cf.describe_option('no.such.key')
    assert 'doc' in self.cf.describe_option('a', _print_desc=False)
    assert 'doc2' in self.cf.describe_option('b', _print_desc=False)
    assert 'precated' in self.cf.describe_option('b', _print_desc=False)
    assert 'doc3' in self.cf.describe_option('c.d.e1', _print_desc=False)
    assert 'doc4' in self.cf.describe_option('c.d.e2', _print_desc=False)
    assert 'vailable' in self.cf.describe_option('f', _print_desc=False)
    assert 'vailable' in self.cf.describe_option('g.h', _print_desc=False)
    assert 'precated' in self.cf.describe_option('g.h', _print_desc=False)
    assert 'k' in self.cf.describe_option('g.h', _print_desc=False)
    assert 'foo' in self.cf.describe_option('l', _print_desc=False)
    assert 'bar' not in self.cf.describe_option('l', _print_desc=False)
    self.cf.set_option('l', 'bar')
    assert 'bar' in self.cf.describe_option('l', _print_desc=False)