@pytest.mark.slow
def test_plot(self):
    _check_plot_works(self.ts.plot, label='foo')
    _check_plot_works(self.ts.plot, use_index=False)
    axes = _check_plot_works(self.ts.plot, rot=0)
    self._check_ticks_props(axes, xrot=0)
    ax = _check_plot_works(self.ts.plot, style='.', logy=True)
    self._check_ax_scales(ax, yaxis='log')
    ax = _check_plot_works(self.ts.plot, style='.', logx=True)
    self._check_ax_scales(ax, xaxis='log')
    ax = _check_plot_works(self.ts.plot, style='.', loglog=True)
    self._check_ax_scales(ax, xaxis='log', yaxis='log')
    _check_plot_works(self.ts[:10].plot.bar)
    _check_plot_works(self.ts.plot.area, stacked=False)
    _check_plot_works(self.iseries.plot)
    for kind in ['line', 'bar', 'barh', 'kde', 'hist', 'box']:
        _check_plot_works(self.series[:5].plot, kind=kind)
    _check_plot_works(self.series[:10].plot.barh)
    ax = _check_plot_works(Series(randn(10)).plot.bar, color='black')
    self._check_colors([ax.patches[0]], facecolors=['black'])
    ax = _check_plot_works(self.ts.plot, subplots=True)
    self._check_axes_shape(ax, axes_num=1, layout=(1, 1))
    ax = _check_plot_works(self.ts.plot, subplots=True, layout=(-1, 1))
    self._check_axes_shape(ax, axes_num=1, layout=(1, 1))
    ax = _check_plot_works(self.ts.plot, subplots=True, layout=(1, -1))
    self._check_axes_shape(ax, axes_num=1, layout=(1, 1))