def test_concat_categorical_coercion(self):
    s1 = pd.Series([1, 2, np.nan], dtype='category')
    s2 = pd.Series([2, 1, 2])
    exp = pd.Series([1, 2, np.nan, 2, 1, 2], dtype='object')
    tm.assert_series_equal(pd.concat([s1, s2], ignore_index=True), exp)
    tm.assert_series_equal(s1.append(s2, ignore_index=True), exp)
    exp = pd.Series([2, 1, 2, 1, 2, np.nan], dtype='object')
    tm.assert_series_equal(pd.concat([s2, s1], ignore_index=True), exp)
    tm.assert_series_equal(s2.append(s1, ignore_index=True), exp)
    s1 = pd.Series([3, 2], dtype='category')
    s2 = pd.Series([2, 1])
    exp = pd.Series([3, 2, 2, 1])
    tm.assert_series_equal(pd.concat([s1, s2], ignore_index=True), exp)
    tm.assert_series_equal(s1.append(s2, ignore_index=True), exp)
    exp = pd.Series([2, 1, 3, 2])
    tm.assert_series_equal(pd.concat([s2, s1], ignore_index=True), exp)
    tm.assert_series_equal(s2.append(s1, ignore_index=True), exp)
    s1 = pd.Series([10, 11, np.nan], dtype='category')
    s2 = pd.Series([1, 3, 2])
    exp = pd.Series([10, 11, np.nan, 1, 3, 2], dtype='object')
    tm.assert_series_equal(pd.concat([s1, s2], ignore_index=True), exp)
    tm.assert_series_equal(s1.append(s2, ignore_index=True), exp)
    exp = pd.Series([1, 3, 2, 10, 11, np.nan], dtype='object')
    tm.assert_series_equal(pd.concat([s2, s1], ignore_index=True), exp)
    tm.assert_series_equal(s2.append(s1, ignore_index=True), exp)
    s1 = pd.Series([10, 11, np.nan], dtype='category')
    s2 = pd.Series(['a', 'b', 'c'])
    exp = pd.Series([10, 11, np.nan, 'a', 'b', 'c'])
    tm.assert_series_equal(pd.concat([s1, s2], ignore_index=True), exp)
    tm.assert_series_equal(s1.append(s2, ignore_index=True), exp)
    exp = pd.Series(['a', 'b', 'c', 10, 11, np.nan])
    tm.assert_series_equal(pd.concat([s2, s1], ignore_index=True), exp)
    tm.assert_series_equal(s2.append(s1, ignore_index=True), exp)
    s1 = pd.Series([10, 11], dtype='category')
    s2 = pd.Series([np.nan, np.nan, np.nan])
    exp = pd.Series([10, 11, np.nan, np.nan, np.nan])
    tm.assert_series_equal(pd.concat([s1, s2], ignore_index=True), exp)
    tm.assert_series_equal(s1.append(s2, ignore_index=True), exp)
    exp = pd.Series([np.nan, np.nan, np.nan, 10, 11])
    tm.assert_series_equal(pd.concat([s2, s1], ignore_index=True), exp)
    tm.assert_series_equal(s2.append(s1, ignore_index=True), exp)