def test_series_append_aware_naive(self):
    rng1 = date_range('1/1/2011 01:00', periods=1, freq='H')
    rng2 = date_range('1/1/2011 02:00', periods=1, freq='H', tz='US/Eastern')
    ser1 = Series(np.random.randn(len(rng1)), index=rng1)
    ser2 = Series(np.random.randn(len(rng2)), index=rng2)
    ts_result = ser1.append(ser2)
    expected = ser1.index.astype(object).append(ser2.index.astype(object))
    assert ts_result.index.equals(expected)
    rng1 = date_range('1/1/2011 01:00', periods=1, freq='H')
    rng2 = range(100)
    ser1 = Series(np.random.randn(len(rng1)), index=rng1)
    ser2 = Series(np.random.randn(len(rng2)), index=rng2)
    ts_result = ser1.append(ser2)
    expected = ser1.index.astype(object).append(ser2.index)
    assert ts_result.index.equals(expected)