def test_is_equal_dtype(self):
    c1 = Categorical(list('aabca'), categories=list('abc'), ordered=False)
    c2 = Categorical(list('aabca'), categories=list('cab'), ordered=False)
    c3 = Categorical(list('aabca'), categories=list('cab'), ordered=True)
    assert c1.is_dtype_equal(c1)
    assert c2.is_dtype_equal(c2)
    assert c3.is_dtype_equal(c3)
    assert c1.is_dtype_equal(c2)
    assert not c1.is_dtype_equal(c3)
    assert not c1.is_dtype_equal(Index(list('aabca')))
    assert not c1.is_dtype_equal(c1.astype(object))
    assert c1.is_dtype_equal(CategoricalIndex(c1))
    assert c1.is_dtype_equal(CategoricalIndex(c1, categories=list('cab')))
    assert not c1.is_dtype_equal(CategoricalIndex(c1, ordered=True))
    s1 = Series(c1)
    s2 = Series(c2)
    s3 = Series(c3)
    assert c1.is_dtype_equal(s1)
    assert c2.is_dtype_equal(s2)
    assert c3.is_dtype_equal(s3)
    assert c1.is_dtype_equal(s2)
    assert not c1.is_dtype_equal(s3)
    assert not c1.is_dtype_equal(s1.astype(object))