@pytest.mark.slow
def test_df_series_secondary_legend(self):
    df = DataFrame(np.random.randn(30, 3), columns=list('abc'))
    s = Series(np.random.randn(30), name='x')
    _, ax = self.plt.subplots()
    ax = df.plot(ax=ax)
    s.plot(legend=True, secondary_y=True, ax=ax)
    self._check_legend_labels(ax, labels=['a', 'b', 'c', 'x (right)'])
    assert ax.get_yaxis().get_visible()
    assert ax.right_ax.get_yaxis().get_visible()
    tm.close()
    _, ax = self.plt.subplots()
    ax = df.plot(ax=ax)
    s.plot(ax=ax, legend=True, secondary_y=True)
    self._check_legend_labels(ax, labels=['a', 'b', 'c', 'x (right)'])
    assert ax.get_yaxis().get_visible()
    assert ax.right_ax.get_yaxis().get_visible()
    tm.close()
    _, ax = self.plt.subplots()
    ax = df.plot(secondary_y=True, ax=ax)
    s.plot(legend=True, secondary_y=True, ax=ax)
    expected = ['a (right)', 'b (right)', 'c (right)', 'x (right)']
    self._check_legend_labels(ax.left_ax, labels=expected)
    assert not ax.left_ax.get_yaxis().get_visible()
    assert ax.get_yaxis().get_visible()
    tm.close()
    _, ax = self.plt.subplots()
    ax = df.plot(secondary_y=True, ax=ax)
    s.plot(ax=ax, legend=True, secondary_y=True)
    expected = ['a (right)', 'b (right)', 'c (right)', 'x (right)']
    self._check_legend_labels(ax.left_ax, expected)
    assert not ax.left_ax.get_yaxis().get_visible()
    assert ax.get_yaxis().get_visible()
    tm.close()
    _, ax = self.plt.subplots()
    ax = df.plot(secondary_y=True, mark_right=False, ax=ax)
    s.plot(ax=ax, legend=True, secondary_y=True)
    expected = ['a', 'b', 'c', 'x (right)']
    self._check_legend_labels(ax.left_ax, expected)
    assert not ax.left_ax.get_yaxis().get_visible()
    assert ax.get_yaxis().get_visible()
    tm.close()