@pytest.mark.parametrize('sep', ['', None])
@pytest.mark.parametrize('dtype_target', ['object', 'category'])
@pytest.mark.parametrize('dtype_caller', ['object', 'category'])
def test_str_cat_categorical(self, index_or_series, dtype_caller, dtype_target, sep):
    box = index_or_series
    s = Index(['a', 'a', 'b', 'a'], dtype=dtype_caller)
    s = s if box == Index else Series(s, index=s)
    t = Index(['b', 'a', 'b', 'c'], dtype=dtype_target)
    expected = Index(['ab', 'aa', 'bb', 'ac'])
    expected = expected if box == Index else Series(expected, index=s)
    result = s.str.cat(t.values, sep=sep)
    assert_series_or_index_equal(result, expected)
    t = Series(t.values, index=s)
    result = s.str.cat(t, sep=sep)
    assert_series_or_index_equal(result, expected)
    result = s.str.cat(t.values, sep=sep)
    assert_series_or_index_equal(result, expected)
    t = Series(t.values, index=t.values)
    expected = Index(['aa', 'aa', 'aa', 'bb', 'bb'])
    expected = expected if box == Index else Series(expected, index=expected.str[:1])
    result = s.str.cat(t, sep=sep)
    assert_series_or_index_equal(result, expected)