def test_simple_normalize_with_separator(self, deep_nested):
    result = json_normalize({'A': {'A': 1, 'B': 2}})
    expected = DataFrame([[1, 2]], columns=['A.A', 'A.B'])
    tm.assert_frame_equal(result.reindex_like(expected), expected)
    result = json_normalize({'A': {'A': 1, 'B': 2}}, sep='_')
    expected = DataFrame([[1, 2]], columns=['A_A', 'A_B'])
    tm.assert_frame_equal(result.reindex_like(expected), expected)
    result = json_normalize({'A': {'A': 1, 'B': 2}}, sep='σ')
    expected = DataFrame([[1, 2]], columns=['AσA', 'AσB'])
    tm.assert_frame_equal(result.reindex_like(expected), expected)
    result = json_normalize(deep_nested, ['states', 'cities'], meta=['country', ['states', 'name']], sep='_')
    expected = Index(['name', 'pop', 'country', 'states_name']).sort_values()
    assert result.columns.sort_values().equals(expected)