def test_comparison_flex_alignment_fill(self):
    left = Series([1, 3, 2], index=list('abc'))
    right = Series([2, 2, 2], index=list('bcd'))
    exp = pd.Series([False, False, True, True], index=list('abcd'))
    tm.assert_series_equal(left.eq(right, fill_value=2), exp)
    exp = pd.Series([True, True, False, False], index=list('abcd'))
    tm.assert_series_equal(left.ne(right, fill_value=2), exp)
    exp = pd.Series([False, False, True, True], index=list('abcd'))
    tm.assert_series_equal(left.le(right, fill_value=0), exp)
    exp = pd.Series([False, False, False, True], index=list('abcd'))
    tm.assert_series_equal(left.lt(right, fill_value=0), exp)
    exp = pd.Series([True, True, True, False], index=list('abcd'))
    tm.assert_series_equal(left.ge(right, fill_value=0), exp)
    exp = pd.Series([True, True, False, False], index=list('abcd'))
    tm.assert_series_equal(left.gt(right, fill_value=0), exp)