def test_tab_completion(self):
    s = Series(list('abcd'))
    assert 'str' in dir(s)
    assert 'dt' not in dir(s)
    assert 'cat' not in dir(s)
    s = Series(date_range('1/1/2015', periods=5))
    assert 'dt' in dir(s)
    assert 'str' not in dir(s)
    assert 'cat' not in dir(s)
    s = Series(list('abbcd'), dtype='category')
    assert 'cat' in dir(s)
    assert 'str' in dir(s)
    assert 'dt' not in dir(s)
    s = Series(date_range('1/1/2015', periods=5)).astype('category')
    assert 'cat' in dir(s)
    assert 'str' not in dir(s)
    assert 'dt' in dir(s)