def test_stack(self):
    unstacked = self.ymd.unstack()
    restacked = unstacked.stack()
    tm.assert_frame_equal(restacked, self.ymd)
    unlexsorted = self.ymd.sort_index(level=2)
    unstacked = unlexsorted.unstack(2)
    restacked = unstacked.stack()
    tm.assert_frame_equal(restacked.sort_index(level=0), self.ymd)
    unlexsorted = unlexsorted[::-1]
    unstacked = unlexsorted.unstack(1)
    restacked = unstacked.stack().swaplevel(1, 2)
    tm.assert_frame_equal(restacked.sort_index(level=0), self.ymd)
    unlexsorted = unlexsorted.swaplevel(0, 1)
    unstacked = unlexsorted.unstack(0).swaplevel(0, 1, axis=1)
    restacked = unstacked.stack(0).swaplevel(1, 2)
    tm.assert_frame_equal(restacked.sort_index(level=0), self.ymd)
    unstacked = self.ymd.unstack()
    unstacked = unstacked.sort_index(axis=1, ascending=False)
    restacked = unstacked.stack()
    tm.assert_frame_equal(restacked, self.ymd)
    unstacked = self.ymd.unstack(1).unstack(1)
    result = unstacked.stack(1)
    expected = self.ymd.unstack()
    tm.assert_frame_equal(result, expected)
    result = unstacked.stack(2)
    expected = self.ymd.unstack(1)
    tm.assert_frame_equal(result, expected)
    result = unstacked.stack(0)
    expected = self.ymd.stack().unstack(1).unstack(1)
    tm.assert_frame_equal(result, expected)
    unstacked = self.ymd.unstack(2).loc[:, ::3]
    stacked = unstacked.stack().stack()
    ymd_stacked = self.ymd.stack()
    tm.assert_series_equal(stacked, ymd_stacked.reindex(stacked.index))
    result = self.ymd.unstack(0).stack(-2)
    expected = self.ymd.unstack(0).stack(0)

    def check(left, right):
        tm.assert_series_equal(left, right)
        assert left.index.is_unique is False
        li, ri = (left.index, right.index)
        tm.assert_index_equal(li, ri)
    df = DataFrame(np.arange(12).reshape(4, 3), index=list('abab'), columns=['1st', '2nd', '3rd'])
    mi = MultiIndex(levels=[['a', 'b'], ['1st', '2nd', '3rd']], codes=[np.tile(np.arange(2).repeat(3), 2), np.tile(np.arange(3), 4)])
    left, right = (df.stack(), Series(np.arange(12), index=mi))
    check(left, right)
    df.columns = ['1st', '2nd', '1st']
    mi = MultiIndex(levels=[['a', 'b'], ['1st', '2nd']], codes=[np.tile(np.arange(2).repeat(3), 2), np.tile([0, 1, 0], 4)])
    left, right = (df.stack(), Series(np.arange(12), index=mi))
    check(left, right)
    tpls = (('a', 2), ('b', 1), ('a', 1), ('b', 2))
    df.index = MultiIndex.from_tuples(tpls)
    mi = MultiIndex(levels=[['a', 'b'], [1, 2], ['1st', '2nd']], codes=[np.tile(np.arange(2).repeat(3), 2), np.repeat([1, 0, 1], [3, 6, 3]), np.tile([0, 1, 0], 4)])
    left, right = (df.stack(), Series(np.arange(12), index=mi))
    check(left, right)