def test_crosstab_normalize(self):
    df = pd.DataFrame({'a': [1, 2, 2, 2, 2], 'b': [3, 3, 4, 4, 4], 'c': [1, 1, np.nan, 1, 1]})
    rindex = pd.Index([1, 2], name='a')
    cindex = pd.Index([3, 4], name='b')
    full_normal = pd.DataFrame([[0.2, 0], [0.2, 0.6]], index=rindex, columns=cindex)
    row_normal = pd.DataFrame([[1.0, 0], [0.25, 0.75]], index=rindex, columns=cindex)
    col_normal = pd.DataFrame([[0.5, 0], [0.5, 1.0]], index=rindex, columns=cindex)
    tm.assert_frame_equal(pd.crosstab(df.a, df.b, normalize='all'), full_normal)
    tm.assert_frame_equal(pd.crosstab(df.a, df.b, normalize=True), full_normal)
    tm.assert_frame_equal(pd.crosstab(df.a, df.b, normalize='index'), row_normal)
    tm.assert_frame_equal(pd.crosstab(df.a, df.b, normalize='columns'), col_normal)
    tm.assert_frame_equal(pd.crosstab(df.a, df.b, normalize=1), pd.crosstab(df.a, df.b, normalize='columns'))
    tm.assert_frame_equal(pd.crosstab(df.a, df.b, normalize=0), pd.crosstab(df.a, df.b, normalize='index'))
    row_normal_margins = pd.DataFrame([[1.0, 0], [0.25, 0.75], [0.4, 0.6]], index=pd.Index([1, 2, 'All'], name='a', dtype='object'), columns=pd.Index([3, 4], name='b', dtype='object'))
    col_normal_margins = pd.DataFrame([[0.5, 0, 0.2], [0.5, 1.0, 0.8]], index=pd.Index([1, 2], name='a', dtype='object'), columns=pd.Index([3, 4, 'All'], name='b', dtype='object'))
    all_normal_margins = pd.DataFrame([[0.2, 0, 0.2], [0.2, 0.6, 0.8], [0.4, 0.6, 1]], index=pd.Index([1, 2, 'All'], name='a', dtype='object'), columns=pd.Index([3, 4, 'All'], name='b', dtype='object'))
    tm.assert_frame_equal(pd.crosstab(df.a, df.b, normalize='index', margins=True), row_normal_margins)
    tm.assert_frame_equal(pd.crosstab(df.a, df.b, normalize='columns', margins=True), col_normal_margins)
    tm.assert_frame_equal(pd.crosstab(df.a, df.b, normalize=True, margins=True), all_normal_margins)
    pd.crosstab([np.array([1, 1, 2, 2]), np.array([1, 2, 1, 2])], np.array([1, 2, 1, 2]))
    norm_counts = pd.DataFrame([[0.25, 0, 0.25], [0.25, 0.5, 0.75], [0.5, 0.5, 1]], index=pd.Index([1, 2, 'All'], name='a', dtype='object'), columns=pd.Index([3, 4, 'All'], name='b'))
    test_case = pd.crosstab(df.a, df.b, df.c, aggfunc='count', normalize='all', margins=True)
    tm.assert_frame_equal(test_case, norm_counts)
    df = pd.DataFrame({'a': [1, 2, 2, 2, 2], 'b': [3, 3, 4, 4, 4], 'c': [0, 4, np.nan, 3, 3]})
    norm_sum = pd.DataFrame([[0, 0, 0.0], [0.4, 0.6, 1], [0.4, 0.6, 1]], index=pd.Index([1, 2, 'All'], name='a', dtype='object'), columns=pd.Index([3, 4, 'All'], name='b', dtype='object'))
    test_case = pd.crosstab(df.a, df.b, df.c, aggfunc=np.sum, normalize='all', margins=True)
    tm.assert_frame_equal(test_case, norm_sum)