def test_to_timedelta(self):
    result = to_timedelta(['', ''])
    assert isna(result).all()
    result = to_timedelta(np.array([np.timedelta64(1, 's')]))
    expected = pd.Index(np.array([np.timedelta64(1, 's')]))
    tm.assert_index_equal(result, expected)
    expected = Series([timedelta(days=1), timedelta(days=1, seconds=1)])
    result = to_timedelta(Series(['1d', '1days 00:00:01']))
    tm.assert_series_equal(result, expected)
    result = TimedeltaIndex([np.timedelta64(0, 'ns'), np.timedelta64(10, 's').astype('m8[ns]')])
    expected = to_timedelta([0, 10], unit='s')
    tm.assert_index_equal(result, expected)
    arr = np.array([1] * 5, dtype='int64')
    result = to_timedelta(arr, unit='s')
    expected = TimedeltaIndex([np.timedelta64(1, 's')] * 5)
    tm.assert_index_equal(result, expected)
    arr = np.array([1] * 5, dtype='int64')
    result = to_timedelta(arr, unit='m')
    expected = TimedeltaIndex([np.timedelta64(1, 'm')] * 5)
    tm.assert_index_equal(result, expected)
    arr = np.array([1] * 5, dtype='int64')
    result = to_timedelta(arr, unit='h')
    expected = TimedeltaIndex([np.timedelta64(1, 'h')] * 5)
    tm.assert_index_equal(result, expected)
    arr = np.array([1] * 5, dtype='timedelta64[s]')
    result = to_timedelta(arr)
    expected = TimedeltaIndex([np.timedelta64(1, 's')] * 5)
    tm.assert_index_equal(result, expected)
    arr = np.array([1] * 5, dtype='timedelta64[D]')
    result = to_timedelta(arr)
    expected = TimedeltaIndex([np.timedelta64(1, 'D')] * 5)
    tm.assert_index_equal(result, expected)