def test_is_dtype(self):
    assert IntervalDtype.is_dtype(self.dtype)
    assert IntervalDtype.is_dtype('interval')
    assert IntervalDtype.is_dtype(IntervalDtype('float64'))
    assert IntervalDtype.is_dtype(IntervalDtype('int64'))
    assert IntervalDtype.is_dtype(IntervalDtype(np.int64))
    assert not IntervalDtype.is_dtype('D')
    assert not IntervalDtype.is_dtype('3D')
    assert not IntervalDtype.is_dtype('U')
    assert not IntervalDtype.is_dtype('S')
    assert not IntervalDtype.is_dtype('foo')
    assert not IntervalDtype.is_dtype('IntervalA')
    assert not IntervalDtype.is_dtype(np.object_)
    assert not IntervalDtype.is_dtype(np.int64)
    assert not IntervalDtype.is_dtype(np.float64)