def test_union_categoricals_sort_false(self):
    c1 = Categorical(['x', 'y', 'z'])
    c2 = Categorical(['a', 'b', 'c'])
    result = union_categoricals([c1, c2], sort_categories=False)
    expected = Categorical(['x', 'y', 'z', 'a', 'b', 'c'], categories=['x', 'y', 'z', 'a', 'b', 'c'])
    tm.assert_categorical_equal(result, expected)
    c1 = Categorical(['a', 'b'], categories=['b', 'a', 'c'])
    c2 = Categorical(['b', 'c'], categories=['b', 'a', 'c'])
    result = union_categoricals([c1, c2], sort_categories=False)
    expected = Categorical(['a', 'b', 'b', 'c'], categories=['b', 'a', 'c'])
    tm.assert_categorical_equal(result, expected)
    c1 = Categorical(['a', 'b'], categories=['a', 'b', 'c'])
    c2 = Categorical(['b', 'c'], categories=['a', 'b', 'c'])
    result = union_categoricals([c1, c2], sort_categories=False)
    expected = Categorical(['a', 'b', 'b', 'c'], categories=['a', 'b', 'c'])
    tm.assert_categorical_equal(result, expected)
    c1 = Categorical(['x', np.nan])
    c2 = Categorical([np.nan, 'b'])
    result = union_categoricals([c1, c2], sort_categories=False)
    expected = Categorical(['x', np.nan, np.nan, 'b'], categories=['x', 'b'])
    tm.assert_categorical_equal(result, expected)
    c1 = Categorical([np.nan])
    c2 = Categorical([np.nan])
    result = union_categoricals([c1, c2], sort_categories=False)
    expected = Categorical([np.nan, np.nan])
    tm.assert_categorical_equal(result, expected)
    c1 = Categorical([])
    c2 = Categorical([])
    result = union_categoricals([c1, c2], sort_categories=False)
    expected = Categorical([])
    tm.assert_categorical_equal(result, expected)
    c1 = Categorical(['b', 'a'], categories=['b', 'a', 'c'], ordered=True)
    c2 = Categorical(['a', 'c'], categories=['b', 'a', 'c'], ordered=True)
    result = union_categoricals([c1, c2], sort_categories=False)
    expected = Categorical(['b', 'a', 'a', 'c'], categories=['b', 'a', 'c'], ordered=True)
    tm.assert_categorical_equal(result, expected)