def test_join_outer(self):
    index = self.create_index()
    other = Int64Index([7, 12, 25, 1, 2, 5])
    other_mono = Int64Index([1, 2, 5, 7, 12, 25])
    res, lidx, ridx = index.join(other, how='outer', return_indexers=True)
    noidx_res = index.join(other, how='outer')
    tm.assert_index_equal(res, noidx_res)
    eres = Int64Index([0, 1, 2, 4, 5, 6, 7, 8, 10, 12, 14, 16, 18, 25])
    elidx = np.array([0, -1, 1, 2, -1, 3, -1, 4, 5, 6, 7, 8, 9, -1], dtype=np.intp)
    eridx = np.array([-1, 3, 4, -1, 5, -1, 0, -1, -1, 1, -1, -1, -1, 2], dtype=np.intp)
    assert isinstance(res, Int64Index)
    tm.assert_index_equal(res, eres)
    tm.assert_numpy_array_equal(lidx, elidx)
    tm.assert_numpy_array_equal(ridx, eridx)
    res, lidx, ridx = index.join(other_mono, how='outer', return_indexers=True)
    noidx_res = index.join(other_mono, how='outer')
    tm.assert_index_equal(res, noidx_res)
    elidx = np.array([0, -1, 1, 2, -1, 3, -1, 4, 5, 6, 7, 8, 9, -1], dtype=np.intp)
    eridx = np.array([-1, 0, 1, -1, 2, -1, 3, -1, -1, 4, -1, -1, -1, 5], dtype=np.intp)
    assert isinstance(res, Int64Index)
    tm.assert_index_equal(res, eres)
    tm.assert_numpy_array_equal(lidx, elidx)
    tm.assert_numpy_array_equal(ridx, eridx)