def test_pad(self):
    values = Series(['a', 'b', np.nan, 'c', np.nan, 'eeeeee'])
    result = values.str.pad(5, side='left')
    exp = Series(['    a', '    b', np.nan, '    c', np.nan, 'eeeeee'])
    tm.assert_almost_equal(result, exp)
    result = values.str.pad(5, side='right')
    exp = Series(['a    ', 'b    ', np.nan, 'c    ', np.nan, 'eeeeee'])
    tm.assert_almost_equal(result, exp)
    result = values.str.pad(5, side='both')
    exp = Series(['  a  ', '  b  ', np.nan, '  c  ', np.nan, 'eeeeee'])
    tm.assert_almost_equal(result, exp)
    mixed = Series(['a', np.nan, 'b', True, datetime.today(), 'ee', None, 1, 2.0])
    rs = Series(mixed).str.pad(5, side='left')
    xp = Series(['    a', np.nan, '    b', np.nan, np.nan, '   ee', np.nan, np.nan, np.nan])
    assert isinstance(rs, Series)
    tm.assert_almost_equal(rs, xp)
    mixed = Series(['a', np.nan, 'b', True, datetime.today(), 'ee', None, 1, 2.0])
    rs = Series(mixed).str.pad(5, side='right')
    xp = Series(['a    ', np.nan, 'b    ', np.nan, np.nan, 'ee   ', np.nan, np.nan, np.nan])
    assert isinstance(rs, Series)
    tm.assert_almost_equal(rs, xp)
    mixed = Series(['a', np.nan, 'b', True, datetime.today(), 'ee', None, 1, 2.0])
    rs = Series(mixed).str.pad(5, side='both')
    xp = Series(['  a  ', np.nan, '  b  ', np.nan, np.nan, '  ee ', np.nan, np.nan, np.nan])
    assert isinstance(rs, Series)
    tm.assert_almost_equal(rs, xp)