def test_ix_categorical_index(self):
    df = DataFrame(np.random.randn(3, 3), index=list('ABC'), columns=list('XYZ'))
    cdf = df.copy()
    cdf.index = CategoricalIndex(df.index)
    cdf.columns = CategoricalIndex(df.columns)
    expect = Series(df.loc['A', :], index=cdf.columns, name='A')
    tm.assert_series_equal(cdf.loc['A', :], expect)
    expect = Series(df.loc[:, 'X'], index=cdf.index, name='X')
    tm.assert_series_equal(cdf.loc[:, 'X'], expect)
    exp_index = CategoricalIndex(list('AB'), categories=['A', 'B', 'C'])
    expect = DataFrame(df.loc[['A', 'B'], :], columns=cdf.columns, index=exp_index)
    tm.assert_frame_equal(cdf.loc[['A', 'B'], :], expect)
    exp_columns = CategoricalIndex(list('XY'), categories=['X', 'Y', 'Z'])
    expect = DataFrame(df.loc[:, ['X', 'Y']], index=cdf.index, columns=exp_columns)
    tm.assert_frame_equal(cdf.loc[:, ['X', 'Y']], expect)
    df = DataFrame(np.random.randn(3, 3), index=list('ABA'), columns=list('XYX'))
    cdf = df.copy()
    cdf.index = CategoricalIndex(df.index)
    cdf.columns = CategoricalIndex(df.columns)
    exp_index = CategoricalIndex(list('AA'), categories=['A', 'B'])
    expect = DataFrame(df.loc['A', :], columns=cdf.columns, index=exp_index)
    tm.assert_frame_equal(cdf.loc['A', :], expect)
    exp_columns = CategoricalIndex(list('XX'), categories=['X', 'Y'])
    expect = DataFrame(df.loc[:, 'X'], index=cdf.index, columns=exp_columns)
    tm.assert_frame_equal(cdf.loc[:, 'X'], expect)
    expect = DataFrame(df.loc[['A', 'B'], :], columns=cdf.columns, index=CategoricalIndex(list('AAB')))
    tm.assert_frame_equal(cdf.loc[['A', 'B'], :], expect)
    expect = DataFrame(df.loc[:, ['X', 'Y']], index=cdf.index, columns=CategoricalIndex(list('XXY')))
    tm.assert_frame_equal(cdf.loc[:, ['X', 'Y']], expect)