def test_concat_multiple_tzs(self):
    ts1 = Timestamp('2015-01-01', tz=None)
    ts2 = Timestamp('2015-01-01', tz='UTC')
    ts3 = Timestamp('2015-01-01', tz='EST')
    df1 = DataFrame(dict(time=[ts1]))
    df2 = DataFrame(dict(time=[ts2]))
    df3 = DataFrame(dict(time=[ts3]))
    results = pd.concat([df1, df2]).reset_index(drop=True)
    expected = DataFrame(dict(time=[ts1, ts2]), dtype=object)
    tm.assert_frame_equal(results, expected)
    results = pd.concat([df1, df3]).reset_index(drop=True)
    expected = DataFrame(dict(time=[ts1, ts3]), dtype=object)
    tm.assert_frame_equal(results, expected)
    results = pd.concat([df2, df3]).reset_index(drop=True)
    expected = DataFrame(dict(time=[ts2, ts3]))
    tm.assert_frame_equal(results, expected)