def test_values(self):
    idx = pd.PeriodIndex([], freq='M')
    exp = np.array([], dtype=np.object)
    tm.assert_numpy_array_equal(idx.values, exp)
    tm.assert_numpy_array_equal(idx.to_numpy(), exp)
    exp = np.array([], dtype=np.int64)
    tm.assert_numpy_array_equal(idx._ndarray_values, exp)
    idx = pd.PeriodIndex(['2011-01', pd.NaT], freq='M')
    exp = np.array([pd.Period('2011-01', freq='M'), pd.NaT], dtype=object)
    tm.assert_numpy_array_equal(idx.values, exp)
    tm.assert_numpy_array_equal(idx.to_numpy(), exp)
    exp = np.array([492, -9223372036854775808], dtype=np.int64)
    tm.assert_numpy_array_equal(idx._ndarray_values, exp)
    idx = pd.PeriodIndex(['2011-01-01', pd.NaT], freq='D')
    exp = np.array([pd.Period('2011-01-01', freq='D'), pd.NaT], dtype=object)
    tm.assert_numpy_array_equal(idx.values, exp)
    tm.assert_numpy_array_equal(idx.to_numpy(), exp)
    exp = np.array([14975, -9223372036854775808], dtype=np.int64)
    tm.assert_numpy_array_equal(idx._ndarray_values, exp)