def test_sort_values_nat_values_in_int_column(self):
    int_values = (2, int(NaT))
    float_values = (2.0, -1.797693e+308)
    df = DataFrame(dict(int=int_values, float=float_values), columns=['int', 'float'])
    df_reversed = DataFrame(dict(int=int_values[::-1], float=float_values[::-1]), columns=['int', 'float'], index=[1, 0])
    df_sorted = df.sort_values(['int', 'float'], na_position='last')
    tm.assert_frame_equal(df_sorted, df_reversed)
    df_sorted = df.sort_values(['int', 'float'], na_position='first')
    tm.assert_frame_equal(df_sorted, df_reversed)
    df_sorted = df.sort_values(['int', 'float'], ascending=False)
    tm.assert_frame_equal(df_sorted, df)
    df = DataFrame(dict(datetime=[Timestamp('2016-01-01'), NaT], float=float_values), columns=['datetime', 'float'])
    df_reversed = DataFrame(dict(datetime=[NaT, Timestamp('2016-01-01')], float=float_values[::-1]), columns=['datetime', 'float'], index=[1, 0])
    df_sorted = df.sort_values(['datetime', 'float'], na_position='first')
    tm.assert_frame_equal(df_sorted, df_reversed)
    df_sorted = df.sort_values(['datetime', 'float'], na_position='last')
    tm.assert_frame_equal(df_sorted, df)
    df_sorted = df.sort_values(['datetime', 'float'], ascending=False)
    tm.assert_frame_equal(df_sorted, df)