def test_take_fill_value(self):
    idx = pd.CategoricalIndex([1, 2, 3], name='xxx')
    result = idx.take(np.array([1, 0, -1]))
    expected = pd.CategoricalIndex([2, 1, 3], name='xxx')
    tm.assert_index_equal(result, expected)
    tm.assert_categorical_equal(result.values, expected.values)
    result = idx.take(np.array([1, 0, -1]), fill_value=True)
    expected = pd.CategoricalIndex([2, 1, np.nan], categories=[1, 2, 3], name='xxx')
    tm.assert_index_equal(result, expected)
    tm.assert_categorical_equal(result.values, expected.values)
    result = idx.take(np.array([1, 0, -1]), allow_fill=False, fill_value=True)
    expected = pd.CategoricalIndex([2, 1, 3], name='xxx')
    tm.assert_index_equal(result, expected)
    tm.assert_categorical_equal(result.values, expected.values)
    idx = pd.CategoricalIndex(list('CBA'), categories=list('ABC'), ordered=True, name='xxx')
    result = idx.take(np.array([1, 0, -1]))
    expected = pd.CategoricalIndex(list('BCA'), categories=list('ABC'), ordered=True, name='xxx')
    tm.assert_index_equal(result, expected)
    tm.assert_categorical_equal(result.values, expected.values)
    result = idx.take(np.array([1, 0, -1]), fill_value=True)
    expected = pd.CategoricalIndex(['B', 'C', np.nan], categories=list('ABC'), ordered=True, name='xxx')
    tm.assert_index_equal(result, expected)
    tm.assert_categorical_equal(result.values, expected.values)
    result = idx.take(np.array([1, 0, -1]), allow_fill=False, fill_value=True)
    expected = pd.CategoricalIndex(list('BCA'), categories=list('ABC'), ordered=True, name='xxx')
    tm.assert_index_equal(result, expected)
    tm.assert_categorical_equal(result.values, expected.values)
    msg = 'When allow_fill=True and fill_value is not None, all indices must be >= -1'
    with pytest.raises(ValueError, match=msg):
        idx.take(np.array([1, 0, -2]), fill_value=True)
    with pytest.raises(ValueError, match=msg):
        idx.take(np.array([1, 0, -5]), fill_value=True)
    with pytest.raises(IndexError):
        idx.take(np.array([1, -5]))