def test_timegrouper_with_reg_groups(self):
    df_original = DataFrame({'Branch': 'A A A A A A A B'.split(), 'Buyer': 'Carl Mark Carl Carl Joe Joe Joe Carl'.split(), 'Quantity': [1, 3, 5, 1, 8, 1, 9, 3], 'Date': [datetime(2013, 1, 1, 13, 0), datetime(2013, 1, 1, 13, 5), datetime(2013, 10, 1, 20, 0), datetime(2013, 10, 2, 10, 0), datetime(2013, 10, 1, 20, 0), datetime(2013, 10, 2, 10, 0), datetime(2013, 12, 2, 12, 0), datetime(2013, 12, 2, 14, 0)]}).set_index('Date')
    df_sorted = df_original.sort_values(by='Quantity', ascending=False)
    for df in [df_original, df_sorted]:
        expected = DataFrame({'Buyer': 'Carl Joe Mark'.split(), 'Quantity': [10, 18, 3], 'Date': [datetime(2013, 12, 31, 0, 0), datetime(2013, 12, 31, 0, 0), datetime(2013, 12, 31, 0, 0)]}).set_index(['Date', 'Buyer'])
        result = df.groupby([pd.Grouper(freq='A'), 'Buyer']).sum()
        tm.assert_frame_equal(result, expected)
        expected = DataFrame({'Buyer': 'Carl Mark Carl Joe'.split(), 'Quantity': [1, 3, 9, 18], 'Date': [datetime(2013, 1, 1, 0, 0), datetime(2013, 1, 1, 0, 0), datetime(2013, 7, 1, 0, 0), datetime(2013, 7, 1, 0, 0)]}).set_index(['Date', 'Buyer'])
        result = df.groupby([pd.Grouper(freq='6MS'), 'Buyer']).sum()
        tm.assert_frame_equal(result, expected)
    df_original = DataFrame({'Branch': 'A A A A A A A B'.split(), 'Buyer': 'Carl Mark Carl Carl Joe Joe Joe Carl'.split(), 'Quantity': [1, 3, 5, 1, 8, 1, 9, 3], 'Date': [datetime(2013, 10, 1, 13, 0), datetime(2013, 10, 1, 13, 5), datetime(2013, 10, 1, 20, 0), datetime(2013, 10, 2, 10, 0), datetime(2013, 10, 1, 20, 0), datetime(2013, 10, 2, 10, 0), datetime(2013, 10, 2, 12, 0), datetime(2013, 10, 2, 14, 0)]}).set_index('Date')
    df_sorted = df_original.sort_values(by='Quantity', ascending=False)
    for df in [df_original, df_sorted]:
        expected = DataFrame({'Buyer': 'Carl Joe Mark Carl Joe'.split(), 'Quantity': [6, 8, 3, 4, 10], 'Date': [datetime(2013, 10, 1, 0, 0), datetime(2013, 10, 1, 0, 0), datetime(2013, 10, 1, 0, 0), datetime(2013, 10, 2, 0, 0), datetime(2013, 10, 2, 0, 0)]}).set_index(['Date', 'Buyer'])
        result = df.groupby([pd.Grouper(freq='1D'), 'Buyer']).sum()
        tm.assert_frame_equal(result, expected)
        result = df.groupby([pd.Grouper(freq='1M'), 'Buyer']).sum()
        expected = DataFrame({'Buyer': 'Carl Joe Mark'.split(), 'Quantity': [10, 18, 3], 'Date': [datetime(2013, 10, 31, 0, 0), datetime(2013, 10, 31, 0, 0), datetime(2013, 10, 31, 0, 0)]}).set_index(['Date', 'Buyer'])
        tm.assert_frame_equal(result, expected)
        df = df.reset_index()
        result = df.groupby([pd.Grouper(freq='1M', key='Date'), 'Buyer']).sum()
        tm.assert_frame_equal(result, expected)
        with pytest.raises(KeyError, match="'The grouper name foo is not found'"):
            df.groupby([pd.Grouper(freq='1M', key='foo'), 'Buyer']).sum()
        df = df.set_index('Date')
        result = df.groupby([pd.Grouper(freq='1M', level='Date'), 'Buyer']).sum()
        tm.assert_frame_equal(result, expected)
        result = df.groupby([pd.Grouper(freq='1M', level=0), 'Buyer']).sum()
        tm.assert_frame_equal(result, expected)
        with pytest.raises(ValueError):
            df.groupby([pd.Grouper(freq='1M', level='foo'), 'Buyer']).sum()
        df = df.copy()
        df['Date'] = df.index + pd.offsets.MonthEnd(2)
        result = df.groupby([pd.Grouper(freq='1M', key='Date'), 'Buyer']).sum()
        expected = DataFrame({'Buyer': 'Carl Joe Mark'.split(), 'Quantity': [10, 18, 3], 'Date': [datetime(2013, 11, 30, 0, 0), datetime(2013, 11, 30, 0, 0), datetime(2013, 11, 30, 0, 0)]}).set_index(['Date', 'Buyer'])
        tm.assert_frame_equal(result, expected)
        with pytest.raises(ValueError):
            df.groupby([pd.Grouper(freq='1M', key='Date', level='Date'), 'Buyer']).sum()
        expected = DataFrame({'Quantity': [31], 'Date': [datetime(2013, 10, 31, 0, 0)]}).set_index('Date')
        result = df.groupby(pd.Grouper(freq='1M')).sum()
        tm.assert_frame_equal(result, expected)
        result = df.groupby([pd.Grouper(freq='1M')]).sum()
        tm.assert_frame_equal(result, expected)
        expected = DataFrame({'Quantity': [31], 'Date': [datetime(2013, 11, 30, 0, 0)]}).set_index('Date')
        result = df.groupby(pd.Grouper(freq='1M', key='Date')).sum()
        tm.assert_frame_equal(result, expected)
        result = df.groupby([pd.Grouper(freq='1M', key='Date')]).sum()
        tm.assert_frame_equal(result, expected)