def test_shift(self, datetime_frame, int_frame):
    shiftedFrame = datetime_frame.shift(5)
    tm.assert_index_equal(shiftedFrame.index, datetime_frame.index)
    shiftedSeries = datetime_frame['A'].shift(5)
    tm.assert_series_equal(shiftedFrame['A'], shiftedSeries)
    shiftedFrame = datetime_frame.shift(-5)
    tm.assert_index_equal(shiftedFrame.index, datetime_frame.index)
    shiftedSeries = datetime_frame['A'].shift(-5)
    tm.assert_series_equal(shiftedFrame['A'], shiftedSeries)
    unshifted = datetime_frame.shift(0)
    tm.assert_frame_equal(unshifted, datetime_frame)
    shiftedFrame = datetime_frame.shift(5, freq=offsets.BDay())
    assert len(shiftedFrame) == len(datetime_frame)
    shiftedFrame2 = datetime_frame.shift(5, freq='B')
    tm.assert_frame_equal(shiftedFrame, shiftedFrame2)
    d = datetime_frame.index[0]
    shifted_d = d + offsets.BDay(5)
    tm.assert_series_equal(datetime_frame.xs(d), shiftedFrame.xs(shifted_d), check_names=False)
    int_shifted = int_frame.shift(1)
    ps = tm.makePeriodFrame()
    shifted = ps.shift(1)
    unshifted = shifted.shift(-1)
    tm.assert_index_equal(shifted.index, ps.index)
    tm.assert_index_equal(unshifted.index, ps.index)
    tm.assert_numpy_array_equal(unshifted.iloc[:, 0].dropna().values, ps.iloc[:-1, 0].values)
    shifted2 = ps.shift(1, 'B')
    shifted3 = ps.shift(1, offsets.BDay())
    tm.assert_frame_equal(shifted2, shifted3)
    tm.assert_frame_equal(ps, shifted2.shift(-1, 'B'))
    msg = 'does not match PeriodIndex freq'
    with pytest.raises(ValueError, match=msg):
        ps.shift(freq='D')
    df = DataFrame(np.random.rand(10, 5))
    expected = pd.concat([DataFrame(np.nan, index=df.index, columns=[0]), df.iloc[:, 0:-1]], ignore_index=True, axis=1)
    result = df.shift(1, axis=1)
    tm.assert_frame_equal(result, expected)
    df = DataFrame(np.random.rand(10, 5))
    expected = pd.concat([DataFrame(np.nan, index=df.index, columns=[0]), df.iloc[:, 0:-1]], ignore_index=True, axis=1)
    result = df.shift(1, axis='columns')
    tm.assert_frame_equal(result, expected)