def test_nargsort(self):
    items = [np.nan] * 5 + list(range(100)) + [np.nan] * 5
    items2 = np.array(items, dtype='O')
    result = nargsort(items, kind='mergesort', ascending=True, na_position='last')
    exp = list(range(5, 105)) + list(range(5)) + list(range(105, 110))
    tm.assert_numpy_array_equal(result, np.array(exp), check_dtype=False)
    result = nargsort(items, kind='mergesort', ascending=True, na_position='first')
    exp = list(range(5)) + list(range(105, 110)) + list(range(5, 105))
    tm.assert_numpy_array_equal(result, np.array(exp), check_dtype=False)
    result = nargsort(items, kind='mergesort', ascending=False, na_position='last')
    exp = list(range(104, 4, -1)) + list(range(5)) + list(range(105, 110))
    tm.assert_numpy_array_equal(result, np.array(exp), check_dtype=False)
    result = nargsort(items, kind='mergesort', ascending=False, na_position='first')
    exp = list(range(5)) + list(range(105, 110)) + list(range(104, 4, -1))
    tm.assert_numpy_array_equal(result, np.array(exp), check_dtype=False)
    result = nargsort(items2, kind='mergesort', ascending=True, na_position='last')
    exp = list(range(5, 105)) + list(range(5)) + list(range(105, 110))
    tm.assert_numpy_array_equal(result, np.array(exp), check_dtype=False)
    result = nargsort(items2, kind='mergesort', ascending=True, na_position='first')
    exp = list(range(5)) + list(range(105, 110)) + list(range(5, 105))
    tm.assert_numpy_array_equal(result, np.array(exp), check_dtype=False)
    result = nargsort(items2, kind='mergesort', ascending=False, na_position='last')
    exp = list(range(104, 4, -1)) + list(range(5)) + list(range(105, 110))
    tm.assert_numpy_array_equal(result, np.array(exp), check_dtype=False)
    result = nargsort(items2, kind='mergesort', ascending=False, na_position='first')
    exp = list(range(5)) + list(range(105, 110)) + list(range(104, 4, -1))
    tm.assert_numpy_array_equal(result, np.array(exp), check_dtype=False)