def test_equals(self):
    s1 = pd.Series([1, 2, 3], index=[0, 2, 1])
    s2 = s1.copy()
    assert s1.equals(s2)
    s1[1] = 99
    assert not s1.equals(s2)
    s1 = pd.Series([1, np.nan, 3, np.nan], index=[0, 2, 1, 3])
    s2 = s1.copy()
    assert s1.equals(s2)
    s2[0] = 9.9
    assert not s1.equals(s2)
    idx = MultiIndex.from_tuples([(0, 'a'), (1, 'b'), (2, 'c')])
    s1 = Series([1, 2, np.nan], index=idx)
    s2 = s1.copy()
    assert s1.equals(s2)
    index = np.random.random(10)
    df1 = DataFrame(np.random.random(10), index=index, columns=['floats'])
    df1['text'] = 'the sky is so blue. we could use more chocolate.'.split()
    df1['start'] = date_range('2000-1-1', periods=10, freq='T')
    df1['end'] = date_range('2000-1-1', periods=10, freq='D')
    df1['diff'] = df1['end'] - df1['start']
    df1['bool'] = np.arange(10) % 3 == 0
    df1.loc[::2] = np.nan
    df2 = df1.copy()
    assert df1['text'].equals(df2['text'])
    assert df1['start'].equals(df2['start'])
    assert df1['end'].equals(df2['end'])
    assert df1['diff'].equals(df2['diff'])
    assert df1['bool'].equals(df2['bool'])
    assert df1.equals(df2)
    assert not df1.equals(object)
    different = df1.copy()
    different['floats'] = different['floats'].astype('float32')
    assert not df1.equals(different)
    different_index = -index
    different = df2.set_index(different_index)
    assert not df1.equals(different)
    different = df2.copy()
    different.columns = df2.columns[::-1]
    assert not df1.equals(different)
    index = pd.date_range('2000-1-1', periods=10, freq='T')
    df1 = df1.set_index(index)
    df2 = df1.copy()
    assert df1.equals(df2)
    df3 = df1.set_index(['text'], append=True)
    df2 = df1.set_index(['text'], append=True)
    assert df3.equals(df2)
    df2 = df1.set_index(['floats'], append=True)
    assert not df3.equals(df2)
    df3 = df1.set_index(['floats'], append=True)
    df2 = df1.set_index(['floats'], append=True)
    assert df3.equals(df2)
    a = pd.Series([False, np.nan])
    b = pd.Series([False, np.nan])
    c = pd.Series(index=range(2), dtype=object)
    d = c.copy()
    e = c.copy()
    f = c.copy()
    c[:-1] = d[:-1] = e[0] = f[0] = False
    assert a.equals(a)
    assert a.equals(b)
    assert a.equals(c)
    assert a.equals(d)
    assert a.equals(e)
    assert e.equals(f)