def test_add_prefix_suffix(self, float_frame):
    with_prefix = float_frame.add_prefix('foo#')
    expected = pd.Index(['foo#{c}'.format(c=c) for c in float_frame.columns])
    tm.assert_index_equal(with_prefix.columns, expected)
    with_suffix = float_frame.add_suffix('#foo')
    expected = pd.Index(['{c}#foo'.format(c=c) for c in float_frame.columns])
    tm.assert_index_equal(with_suffix.columns, expected)
    with_pct_prefix = float_frame.add_prefix('%')
    expected = pd.Index(['%{c}'.format(c=c) for c in float_frame.columns])
    tm.assert_index_equal(with_pct_prefix.columns, expected)
    with_pct_suffix = float_frame.add_suffix('%')
    expected = pd.Index(['{c}%'.format(c=c) for c in float_frame.columns])
    tm.assert_index_equal(with_pct_suffix.columns, expected)