def test_df_where_change_dtype(self):
    df = DataFrame(np.arange(2 * 3).reshape(2, 3), columns=list('ABC'))
    mask = np.array([[True, False, False], [False, False, True]])
    result = df.where(mask)
    expected = DataFrame([[0, np.nan, np.nan], [np.nan, np.nan, 5]], columns=list('ABC'))
    tm.assert_frame_equal(result, expected)
    df.A = df.A.astype('category')
    df.B = df.B.astype('category')
    df.C = df.C.astype('category')
    result = df.where(mask)
    A = pd.Categorical([0, np.nan], categories=[0, 3])
    B = pd.Categorical([np.nan, np.nan], categories=[1, 4])
    C = pd.Categorical([np.nan, 5], categories=[2, 5])
    expected = DataFrame({'A': A, 'B': B, 'C': C})
    tm.assert_frame_equal(result, expected)