def test_concat_categorical_multi_coercion(self):
    s1 = pd.Series([1, 3], dtype='category')
    s2 = pd.Series([3, 4], dtype='category')
    s3 = pd.Series([2, 3])
    s4 = pd.Series([2, 2], dtype='category')
    s5 = pd.Series([1, np.nan])
    s6 = pd.Series([1, 3, 2], dtype='category')
    exp = pd.Series([1, 3, 3, 4, 2, 3, 2, 2, 1, np.nan, 1, 3, 2])
    res = pd.concat([s1, s2, s3, s4, s5, s6], ignore_index=True)
    tm.assert_series_equal(res, exp)
    res = s1.append([s2, s3, s4, s5, s6], ignore_index=True)
    tm.assert_series_equal(res, exp)
    exp = pd.Series([1, 3, 2, 1, np.nan, 2, 2, 2, 3, 3, 4, 1, 3])
    res = pd.concat([s6, s5, s4, s3, s2, s1], ignore_index=True)
    tm.assert_series_equal(res, exp)
    res = s6.append([s5, s4, s3, s2, s1], ignore_index=True)
    tm.assert_series_equal(res, exp)