def test_label(self):
    s = Series([1, 2])
    _, ax = self.plt.subplots()
    ax = s.plot(label='LABEL', legend=True, ax=ax)
    self._check_legend_labels(ax, labels=['LABEL'])
    self.plt.close()
    _, ax = self.plt.subplots()
    ax = s.plot(legend=True, ax=ax)
    self._check_legend_labels(ax, labels=['None'])
    self.plt.close()
    s.name = 'NAME'
    _, ax = self.plt.subplots()
    ax = s.plot(legend=True, ax=ax)
    self._check_legend_labels(ax, labels=['NAME'])
    self.plt.close()
    _, ax = self.plt.subplots()
    ax = s.plot(legend=True, label='LABEL', ax=ax)
    self._check_legend_labels(ax, labels=['LABEL'])
    self.plt.close()
    _, ax = self.plt.subplots()
    ax = s.plot(legend=False, label='LABEL', ax=ax)
    assert ax.get_legend() is None
    ax.legend()
    self._check_legend_labels(ax, labels=['LABEL'])