def test_comparison_flex_alignment(self):
    left = Series([1, 3, 2], index=list('abc'))
    right = Series([2, 2, 2], index=list('bcd'))
    exp = pd.Series([False, False, True, False], index=list('abcd'))
    tm.assert_series_equal(left.eq(right), exp)
    exp = pd.Series([True, True, False, True], index=list('abcd'))
    tm.assert_series_equal(left.ne(right), exp)
    exp = pd.Series([False, False, True, False], index=list('abcd'))
    tm.assert_series_equal(left.le(right), exp)
    exp = pd.Series([False, False, False, False], index=list('abcd'))
    tm.assert_series_equal(left.lt(right), exp)
    exp = pd.Series([False, True, True, False], index=list('abcd'))
    tm.assert_series_equal(left.ge(right), exp)
    exp = pd.Series([False, True, False, False], index=list('abcd'))
    tm.assert_series_equal(left.gt(right), exp)