def test_astype_from_categorical(self):
    items = ['a', 'b', 'c', 'a']
    s = Series(items)
    exp = Series(Categorical(items))
    res = s.astype('category')
    tm.assert_series_equal(res, exp)
    items = [1, 2, 3, 1]
    s = Series(items)
    exp = Series(Categorical(items))
    res = s.astype('category')
    tm.assert_series_equal(res, exp)
    df = DataFrame({'cats': [1, 2, 3, 4, 5, 6], 'vals': [1, 2, 3, 4, 5, 6]})
    cats = Categorical([1, 2, 3, 4, 5, 6])
    exp_df = DataFrame({'cats': cats, 'vals': [1, 2, 3, 4, 5, 6]})
    df['cats'] = df['cats'].astype('category')
    tm.assert_frame_equal(exp_df, df)
    df = DataFrame({'cats': ['a', 'b', 'b', 'a', 'a', 'd'], 'vals': [1, 2, 3, 4, 5, 6]})
    cats = Categorical(['a', 'b', 'b', 'a', 'a', 'd'])
    exp_df = DataFrame({'cats': cats, 'vals': [1, 2, 3, 4, 5, 6]})
    df['cats'] = df['cats'].astype('category')
    tm.assert_frame_equal(exp_df, df)
    lst = ['a', 'b', 'c', 'a']
    s = Series(lst)
    exp = Series(Categorical(lst, ordered=True))
    res = s.astype(CategoricalDtype(None, ordered=True))
    tm.assert_series_equal(res, exp)
    exp = Series(Categorical(lst, categories=list('abcdef'), ordered=True))
    res = s.astype(CategoricalDtype(list('abcdef'), ordered=True))
    tm.assert_series_equal(res, exp)