def test_get(self):
    values = Series(['a_b_c', 'c_d_e', np.nan, 'f_g_h'])
    result = values.str.split('_').str.get(1)
    expected = Series(['b', 'd', np.nan, 'g'])
    tm.assert_series_equal(result, expected)
    mixed = Series(['a_b_c', np.nan, 'c_d_e', True, datetime.today(), None, 1, 2.0])
    rs = Series(mixed).str.split('_').str.get(1)
    xp = Series(['b', np.nan, 'd', np.nan, np.nan, np.nan, np.nan, np.nan])
    assert isinstance(rs, Series)
    tm.assert_almost_equal(rs, xp)
    values = Series(['1_2_3_4_5', '6_7_8_9_10', '11_12'])
    result = values.str.split('_').str.get(2)
    expected = Series(['3', '8', np.nan])
    tm.assert_series_equal(result, expected)
    result = values.str.split('_').str.get(-3)
    expected = Series(['3', '8', np.nan])
    tm.assert_series_equal(result, expected)