def test_unique_index_series(self):
    c = Categorical([3, 1, 2, 2, 1], categories=[3, 2, 1])
    exp = Categorical([3, 1, 2], categories=[3, 1, 2])
    tm.assert_categorical_equal(c.unique(), exp)
    tm.assert_index_equal(Index(c).unique(), Index(exp))
    tm.assert_categorical_equal(Series(c).unique(), exp)
    c = Categorical([1, 1, 2, 2], categories=[3, 2, 1])
    exp = Categorical([1, 2], categories=[1, 2])
    tm.assert_categorical_equal(c.unique(), exp)
    tm.assert_index_equal(Index(c).unique(), Index(exp))
    tm.assert_categorical_equal(Series(c).unique(), exp)
    c = Categorical([3, 1, 2, 2, 1], categories=[3, 2, 1], ordered=True)
    exp = Categorical([3, 1, 2], categories=[3, 2, 1], ordered=True)
    tm.assert_categorical_equal(c.unique(), exp)
    tm.assert_index_equal(Index(c).unique(), Index(exp))
    tm.assert_categorical_equal(Series(c).unique(), exp)