def test_append_all_nans(self, setup_path):
    with ensure_clean_store(setup_path) as store:
        df = DataFrame({'A1': np.random.randn(20), 'A2': np.random.randn(20)}, index=np.arange(20))
        df.loc[0:15, :] = np.nan
        _maybe_remove(store, 'df')
        store.append('df', df[:10], dropna=True)
        store.append('df', df[10:], dropna=True)
        tm.assert_frame_equal(store['df'], df[-4:])
        _maybe_remove(store, 'df2')
        store.append('df2', df[:10], dropna=False)
        store.append('df2', df[10:], dropna=False)
        tm.assert_frame_equal(store['df2'], df)
        pd.set_option('io.hdf.dropna_table', False)
        _maybe_remove(store, 'df3')
        store.append('df3', df[:10])
        store.append('df3', df[10:])
        tm.assert_frame_equal(store['df3'], df)
        pd.set_option('io.hdf.dropna_table', True)
        _maybe_remove(store, 'df4')
        store.append('df4', df[:10])
        store.append('df4', df[10:])
        tm.assert_frame_equal(store['df4'], df[-4:])
        df = DataFrame({'A1': np.random.randn(20), 'A2': np.random.randn(20), 'B': 'foo', 'C': 'bar'}, index=np.arange(20))
        df.loc[0:15, :] = np.nan
        _maybe_remove(store, 'df')
        store.append('df', df[:10], dropna=True)
        store.append('df', df[10:], dropna=True)
        tm.assert_frame_equal(store['df'], df)
        _maybe_remove(store, 'df2')
        store.append('df2', df[:10], dropna=False)
        store.append('df2', df[10:], dropna=False)
        tm.assert_frame_equal(store['df2'], df)
        df = DataFrame({'A1': np.random.randn(20), 'A2': np.random.randn(20), 'B': 'foo', 'C': 'bar', 'D': Timestamp('20010101'), 'E': datetime.datetime(2001, 1, 2, 0, 0)}, index=np.arange(20))
        df.loc[0:15, :] = np.nan
        _maybe_remove(store, 'df')
        store.append('df', df[:10], dropna=True)
        store.append('df', df[10:], dropna=True)
        tm.assert_frame_equal(store['df'], df)
        _maybe_remove(store, 'df2')
        store.append('df2', df[:10], dropna=False)
        store.append('df2', df[10:], dropna=False)
        tm.assert_frame_equal(store['df2'], df)
    df_with_missing = DataFrame({'col1': [0, np.nan, 2], 'col2': [1, np.nan, np.nan]})
    with ensure_clean_path(setup_path) as path:
        df_with_missing.to_hdf(path, 'df_with_missing', format='table')
        reloaded = read_hdf(path, 'df_with_missing')
        tm.assert_frame_equal(df_with_missing, reloaded)