def test_regex_replace_series_of_regexes(self, mix_abc):
    df = DataFrame(mix_abc)
    s1 = Series({'b': '\\s*\\.\\s*'})
    s2 = Series({'b': np.nan})
    res = df.replace(s1, s2, regex=True)
    res2 = df.copy()
    res2.replace(s1, s2, inplace=True, regex=True)
    res3 = df.copy()
    res3.replace(regex=s1, value=s2, inplace=True)
    expec = DataFrame({'a': mix_abc['a'], 'b': ['a', 'b', np.nan, np.nan], 'c': mix_abc['c']})
    tm.assert_frame_equal(res, expec)
    tm.assert_frame_equal(res2, expec)
    tm.assert_frame_equal(res3, expec)