def test_schema_support(self):
    df = DataFrame({'col1': [1, 2], 'col2': [0.1, 0.2], 'col3': ['a', 'n']})
    self.conn.execute('DROP SCHEMA IF EXISTS other CASCADE;')
    self.conn.execute('CREATE SCHEMA other;')
    df.to_sql('test_schema_public', self.conn, index=False)
    df.to_sql('test_schema_public_explicit', self.conn, index=False, schema='public')
    df.to_sql('test_schema_other', self.conn, index=False, schema='other')
    res1 = sql.read_sql_table('test_schema_public', self.conn)
    tm.assert_frame_equal(df, res1)
    res2 = sql.read_sql_table('test_schema_public_explicit', self.conn)
    tm.assert_frame_equal(df, res2)
    res3 = sql.read_sql_table('test_schema_public_explicit', self.conn, schema='public')
    tm.assert_frame_equal(df, res3)
    res4 = sql.read_sql_table('test_schema_other', self.conn, schema='other')
    tm.assert_frame_equal(df, res4)
    msg = 'Table test_schema_other not found'
    with pytest.raises(ValueError, match=msg):
        sql.read_sql_table('test_schema_other', self.conn, schema='public')
    self.conn.execute('DROP SCHEMA IF EXISTS other CASCADE;')
    self.conn.execute('CREATE SCHEMA other;')
    df.to_sql('test_schema_other', self.conn, schema='other', index=False)
    df.to_sql('test_schema_other', self.conn, schema='other', index=False, if_exists='replace')
    df.to_sql('test_schema_other', self.conn, schema='other', index=False, if_exists='append')
    res = sql.read_sql_table('test_schema_other', self.conn, schema='other')
    tm.assert_frame_equal(concat([df, df], ignore_index=True), res)
    if isinstance(self.conn, sqlalchemy.engine.Engine):
        engine2 = self.connect()
        meta = sqlalchemy.MetaData(engine2, schema='other')
        pdsql = sql.SQLDatabase(engine2, meta=meta)
        pdsql.to_sql(df, 'test_schema_other2', index=False)
        pdsql.to_sql(df, 'test_schema_other2', index=False, if_exists='replace')
        pdsql.to_sql(df, 'test_schema_other2', index=False, if_exists='append')
        res1 = sql.read_sql_table('test_schema_other2', self.conn, schema='other')
        res2 = pdsql.read_table('test_schema_other2')
        tm.assert_frame_equal(res1, res2)