def test_astype(self):
    idx = TimedeltaIndex([100000000000000.0, 'NaT', NaT, np.NaN])
    result = idx.astype(object)
    expected = Index([Timedelta('1 days 03:46:40')] + [NaT] * 3, dtype=object)
    tm.assert_index_equal(result, expected)
    result = idx.astype(int)
    expected = Int64Index([100000000000000] + [-9223372036854775808] * 3, dtype=np.int64)
    tm.assert_index_equal(result, expected)
    result = idx.astype(str)
    expected = Index((str(x) for x in idx))
    tm.assert_index_equal(result, expected)
    rng = timedelta_range('1 days', periods=10)
    result = rng.astype('i8')
    tm.assert_index_equal(result, Index(rng.asi8))
    tm.assert_numpy_array_equal(rng.asi8, result.values)