def test_replace_gh5319(self):
    ser = pd.Series([0, np.nan, 2, 3, 4])
    expected = ser.ffill()
    result = ser.replace([np.nan])
    tm.assert_series_equal(result, expected)
    ser = pd.Series([0, np.nan, 2, 3, 4])
    expected = ser.ffill()
    result = ser.replace(np.nan)
    tm.assert_series_equal(result, expected)
    ser = pd.Series(pd.date_range('20130101', periods=5))
    expected = ser.copy()
    expected.loc[2] = pd.Timestamp('20120101')
    result = ser.replace({pd.Timestamp('20130103'): pd.Timestamp('20120101')})
    tm.assert_series_equal(result, expected)
    result = ser.replace(pd.Timestamp('20130103'), pd.Timestamp('20120101'))
    tm.assert_series_equal(result, expected)
    ts = pd.Timestamp('2015/01/01', tz='UTC')
    s = pd.Series([pd.NaT, pd.Timestamp('2015/01/01', tz='UTC')])
    result = s.replace([np.nan, pd.NaT], pd.Timestamp.min)
    expected = pd.Series([pd.Timestamp.min, ts], dtype=object)
    tm.assert_series_equal(expected, result)