def test_fillna_categorical_nan(self):
    cat = Categorical([np.nan, 2, np.nan])
    val = Categorical([np.nan, np.nan, np.nan])
    df = DataFrame({'cats': cat, 'vals': val})
    with tm.assert_produces_warning(RuntimeWarning):
        res = df.fillna(df.median())
    v_exp = [np.nan, np.nan, np.nan]
    df_exp = DataFrame({'cats': [2, 2, 2], 'vals': v_exp}, dtype='category')
    tm.assert_frame_equal(res, df_exp)
    result = df.cats.fillna(np.nan)
    tm.assert_series_equal(result, df.cats)
    result = df.vals.fillna(np.nan)
    tm.assert_series_equal(result, df.vals)
    idx = pd.DatetimeIndex(['2011-01-01 09:00', '2016-01-01 23:45', '2011-01-01 09:00', pd.NaT, pd.NaT])
    df = DataFrame({'a': Categorical(idx)})
    tm.assert_frame_equal(df.fillna(value=pd.NaT), df)
    idx = pd.PeriodIndex(['2011-01', '2011-01', '2011-01', pd.NaT, pd.NaT], freq='M')
    df = DataFrame({'a': Categorical(idx)})
    tm.assert_frame_equal(df.fillna(value=pd.NaT), df)
    idx = pd.TimedeltaIndex(['1 days', '2 days', '1 days', pd.NaT, pd.NaT])
    df = DataFrame({'a': Categorical(idx)})
    tm.assert_frame_equal(df.fillna(value=pd.NaT), df)