def test_integer_array_plot(self):
    arr = integer_array([1, 2, 3, 4], dtype='UInt32')
    s = Series(arr)
    _check_plot_works(s.plot.line)
    _check_plot_works(s.plot.bar)
    _check_plot_works(s.plot.hist)
    _check_plot_works(s.plot.pie)
    df = DataFrame({'x': arr, 'y': arr})
    _check_plot_works(df.plot.line)
    _check_plot_works(df.plot.bar)
    _check_plot_works(df.plot.hist)
    _check_plot_works(df.plot.pie, y='y')
    _check_plot_works(df.plot.scatter, x='x', y='y')
    _check_plot_works(df.plot.hexbin, x='x', y='y')