def test_replace_mixed_types(self):
    s = pd.Series(np.arange(5), dtype='int64')

    def check_replace(to_rep, val, expected):
        sc = s.copy()
        r = s.replace(to_rep, val)
        sc.replace(to_rep, val, inplace=True)
        tm.assert_series_equal(expected, r)
        tm.assert_series_equal(expected, sc)
    e = pd.Series([0.0, 1.0, 2.0, 3.0, 4.0])
    tr, v = ([3], [3.0])
    check_replace(tr, v, e)
    e = pd.Series([0, 1, 2, 3.5, 4])
    tr, v = ([3], [3.5])
    check_replace(tr, v, e)
    e = pd.Series([0, 1, 2, 3.5, 'a'])
    tr, v = ([3, 4], [3.5, 'a'])
    check_replace(tr, v, e)
    e = pd.Series([0, 1, 2, 3.5, pd.Timestamp('20130101')])
    tr, v = ([3, 4], [3.5, pd.Timestamp('20130101')])
    check_replace(tr, v, e)
    e = pd.Series([0, 1, 2, 3.5, True], dtype='object')
    tr, v = ([3, 4], [3.5, True])
    check_replace(tr, v, e)
    dr = pd.date_range('1/1/2001', '1/10/2001', freq='D').to_series().reset_index(drop=True)
    result = dr.astype(object).replace([dr[0], dr[1], dr[2]], [1.0, 2, 'a'])
    expected = pd.Series([1.0, 2, 'a'] + dr[3:].tolist(), dtype=object)
    tm.assert_series_equal(result, expected)